// In-memory, per-session order state (no database, lost on restart).
// Each chat session gets its own separate draft order. Session ids are random and generated by the server only.
const crypto = require('crypto');

const SESSION_ID_PATTERN = /^[a-f0-9]{32}$/;
const SESSION_TTL_MS = 2 * 60 * 60 * 1000; // idle sessions expire after 2 hours
const MAX_SESSIONS = 1000;

const sessions = new Map(); // sessionId -> { state, lastSeen }

function newOrderState() {
  return {
    items: [], // cart lines: { lineId, id, name, quantity, options: { <optionName>: <choice> } }
    lineCounter: 0, // used to give each cart line a unique lineId
    declinedSuggestions: [], // item ids the customer said no to (never suggested again in this session)
    orderType: null, // 'pickup' | 'delivery'
    pickupTime: null, // 'HH:MM' (24-hour), pickup orders only, optional
    pickupTimeDeclined: false, // the customer said they have no pickup time preference
    addressExtrasDeclined: false, // delivery: the customer said no apartment/unit or instructions
    addressReadBack: false, // delivery: the code has read the captured details back to the customer
    addressConfirmed: false, // delivery: the customer clearly said yes to the read-back (reset by ANY change)
    reviewShownVersion: null, // reviewVersion of the last order review shown to the customer
    confirmedVersion: null, // reviewVersion that the customer confirmed with the button
    customer: { name: null, phone: null, address: null }, // address (delivery): { block, house, street, apartment, landmark, instructions }
    discount: null,
    totals: null, // { foodSubtotal, discountAmount, deliveryFee, tax, total } from the pricing function, updated on every change
    total: 0,
    confirmed: false,
    status: 'draft'
  };
}

function prune(now) {
  for (const [id, entry] of sessions) {
    if (now - entry.lastSeen > SESSION_TTL_MS) sessions.delete(id);
  }
  while (sessions.size >= MAX_SESSIONS) {
    let oldestId = null;
    for (const [id, entry] of sessions) {
      if (oldestId === null || entry.lastSeen < sessions.get(oldestId).lastSeen) oldestId = id;
    }
    sessions.delete(oldestId);
  }
}

// Returns { sessionId, state }. A missing, malformed or unknown id gets a brand-new empty session
// with a fresh server-generated id (client-supplied ids are never adopted).
function getOrCreateSession(sessionId) {
  const now = Date.now();
  if (typeof sessionId === 'string' && SESSION_ID_PATTERN.test(sessionId)) {
    const entry = sessions.get(sessionId);
    if (entry && now - entry.lastSeen <= SESSION_TTL_MS) {
      entry.lastSeen = now;
      return { sessionId, state: entry.state };
    }
  }
  prune(now);
  const id = crypto.randomBytes(16).toString('hex');
  const state = newOrderState();
  sessions.set(id, { state, lastSeen: now });
  return { sessionId: id, state };
}

// Looks up an existing session WITHOUT creating one (used by the confirm endpoint). Returns { sessionId, state } or null.
function getExistingSession(sessionId) {
  if (typeof sessionId !== 'string' || !SESSION_ID_PATTERN.test(sessionId)) return null;
  const entry = sessions.get(sessionId);
  const now = Date.now();
  if (!entry || now - entry.lastSeen > SESSION_TTL_MS) return null;
  entry.lastSeen = now;
  return { sessionId, state: entry.state };
}

module.exports = { getOrCreateSession, getExistingSession };
