const ROOT = require('path').join(__dirname, '..', '..');
const assert = require('assert'); const dir = __dirname; const fs = require('fs'); const cp = require('child_process');
const L = require(dir + '/lib.js'); const { sessions, base } = L.boot(3077);
const { renderPrompt, promptFacts } = require(ROOT + '/backend/facts'); const { executeTool } = require(ROOT + '/backend/tools');
const realRestFile = ROOT + '/data/restaurant.json'; const restKeep = fs.readFileSync(realRestFile, 'utf8');
const restFile = global.__ORDERS_DIR + '/restaurant.json'; fs.writeFileSync(restFile, restKeep); require(ROOT + '/backend/data').setRestaurantPathForTests(restFile); // temp copy only: the real data/restaurant.json is never written
const ordersFile = global.__ORDERS_FILE; const ordersKeep = fs.readFileSync(ordersFile, 'utf8'); process.on('exit', () => fs.writeFileSync(ordersFile, ordersKeep));
const template = fs.readFileSync(ROOT + '/prompts/system-prompt.md', 'utf8'); const real = JSON.parse(restKeep);
const sleep = (ms) => new Promise(r => setTimeout(r, ms)); const run = (state, name, args, latest) => executeTool(name, args, { state, latestMessage: latest }); const mild = [{ name: 'spice', choice: 'mild' }];
let lastSys = ''; global.__STUB = async ({ contents, config }) => { lastSys = config.systemInstruction; const res = L.lastToolResults(contents); return res ? L.text(res[0].response.customerMessage) : L.text('ok'); };
const withRestaurant = async (obj, fn) => { fs.writeFileSync(restFile, JSON.stringify(obj, null, 2)); try { return await fn(); } finally { fs.writeFileSync(restFile, restKeep); } };
(async () => { await sleep(500);
  // 1) the prompt sent to the model carries the values from restaurant.json
  await L.post(base, { message: 'hello' });
  for (const line of ['You are **Dastarkhwan Assistant**, the friendly and efficient virtual assistant for **Karachi Dastarkhwan**, a restaurant in Gulshan-e-Iqbal, Karachi.', '- Name: Karachi Dastarkhwan', '- Location: Gulshan-e-Iqbal, Karachi', '- Hours: daily from 12 noon to 11 PM', '- Delivery: Gulshan-e-Iqbal Blocks 1–5 only', '- Delivery fee: 150 PKR', '- Pickup: free', '- Payment: cash only, on pickup or delivery', '- Tax: none (0%) (the system includes it in totals; never calculate it yourself)', '- Preparation time: do not promise or estimate any preparation or delivery time']) assert(lastSys.includes(line), 'missing: ' + line);
  assert(!lastSys.includes('{{') && !lastSys.includes('}}'));
  const oldPrompt = cp.spawnSync('git', ['show', '04491e3:prompts/system-prompt.md'], { cwd: ROOT, encoding: 'utf8' }).stdout; for (const line of oldPrompt.split('\n').filter(l => /^- (Hours|Delivery|Delivery fee|Pickup|Payment|Preparation time|Name|Location):/.test(l))) assert(lastSys.includes(line), 'value changed vs part 3: ' + line);
  console.log('1) the prompt the model receives contains every fact from restaurant.json (name, location, hours "12 noon to 11 PM", delivery "Gulshan-e-Iqbal Blocks 1–5 only", fee 150 PKR, pickup free, payment, tax, no-promised-time rule); no {{placeholder}} left; the wording is IDENTICAL to the old hardcoded lines (values unchanged): PASS');
  // 2) changing restaurant.json changes the prompt (pure function, then end-to-end)
  const alt = { ...real, name: 'Test Kitchen', area: 'Clifton', city: 'Lahore', hours: { open: '10:30', close: '22:00' }, delivery: { blocks: [2, 3, 4, 6], fee: 200 }, pickup: { fee: 20 }, payment: { method: 'card', timing: 'on delivery' }, taxRate: 0.05, promisePreparationTime: true };
  const out = renderPrompt(template, alt); for (const line of ['**Test Kitchen**, a restaurant in Clifton, Lahore.', '- Hours: daily from 10:30 AM to 10 PM', '- Delivery: Clifton Blocks 2, 3, 4 and 6 only', '- Delivery fee: 200 PKR', '- Pickup: 20 PKR', '- Payment: card only, on delivery', '- Tax: 5%', '- Preparation time: only mention preparation times that the approved facts state']) assert(out.includes(line), line);
  for (const old of ['12 noon', '11 PM', '150 PKR', 'Blocks 1–5', 'cash only', 'Karachi']) assert(!out.includes(old), 'old value survived: ' + old);
  assert.throws(() => renderPrompt('Hello {{NOPE}}', real), /unknown prompt placeholder NOPE/); assert.throws(() => renderPrompt('Hello {{name}}', real), /malformed/);
  await withRestaurant(alt, async () => { await L.post(base, { message: 'hello again' }); assert(lastSys.includes('- Hours: daily from 10:30 AM to 10 PM') && lastSys.includes('- Delivery fee: 200 PKR') && !lastSys.includes('12 noon')); });
  await L.post(base, { message: 'and back' }); assert(lastSys.includes('- Hours: daily from 12 noon to 11 PM'));
  console.log('2) a changed copy of restaurant.json (name, area, hours 10:30-22:00, blocks 2/3/4/6, fee 200, pickup 20, card on delivery, tax 5%, prep time) -> every line of the prompt changes, no old value survives; unknown/malformed placeholders throw; end-to-end the NEXT chat request uses the new file and the old values return after restoring: PASS');
  // 3) the code's messages follow the file too
  await withRestaurant(alt, async () => {
    const s = L.lastToolResults ? sessions.getOrCreateSession().state : null; run(s, 'addItemToCart', { itemId: 'NAN01', quantity: 1 }); run(s, 'setOrderType', { orderType: 'pickup' });
    const early = run(s, 'setCustomerDetails', { pickupTime: '10:00' }); assert.strictEqual(early.customerMessage, "Sorry, we're open daily from 10:30 AM to 10:00 PM, so I can only note a pickup time within those hours."); assert.strictEqual(run(s, 'setCustomerDetails', { pickupTime: '10:30' }).ok, true); assert.strictEqual(run(s, 'setCustomerDetails', { pickupTime: '21:59' }).ok, true); assert.strictEqual(run(s, 'setCustomerDetails', { pickupTime: '22:00' }).ok, false);
    assert.deepStrictEqual([s.totals.deliveryFee, s.totals.tax, s.totals.total], [20, 2, 62]); // 40 food + pickup fee 20 + tax round(40*0.05)=2
    const d = sessions.getOrCreateSession().state; run(d, 'addItemToCart', { itemId: 'NAN01', quantity: 1 }); run(d, 'setOrderType', { orderType: 'delivery' }); assert.deepStrictEqual([d.totals.deliveryFee, d.totals.tax, d.totals.total], [200, 2, 242]); // 40 + 200 + round(40*0.05)=2
    assert.strictEqual(run(d, 'setCustomerDetails', { block: '5' }).error, 'outside_delivery_area'); assert(run(d, 'setCustomerDetails', { block: '5' }).customerMessage.includes('Clifton Blocks 2 to 6')); assert.strictEqual(run(d, 'setCustomerDetails', { block: '6', name: 'Ali' }).ok, true);
    const e = sessions.getOrCreateSession().state; run(e, 'addItemToCart', { itemId: 'NAN01', quantity: 1 }); run(e, 'setOrderType', { orderType: 'delivery' }); const miss = run(e, 'setCustomerDetails', { name: 'Ali' }); assert.strictEqual(miss.missingDetails.find(m => m.field === 'block').ask, 'Which block of Clifton is it in (2 to 6)?'); assert(miss.customerMessage.includes('block number (2 to 6)'));
    assert.strictEqual(run(sessions.getOrCreateSession().state, 'setCustomerDetails', { area: 'Gulshan' }).error, 'order_type_needed');
    const rv = (() => { run(d, 'setCustomerDetails', { phone: '03001234567', houseOrFlat: '7', street: 'Main' }); run(d, 'readBackAddress', {}); run(d, 'confirmAddress', {}, 'yes'); return run(d, 'getOrderReview', {}); })(); assert.strictEqual(rv.ok, true); assert.strictEqual(rv.review.payment, 'Card on delivery'); assert(rv.customerMessage.includes('Payment: card on delivery') && rv.customerMessage.includes('Delivery address: House or flat 7, Main, Block 6, Clifton, Lahore'));
  });
  console.log('3) code messages follow the file: pickup hours "10:30 AM to 10:00 PM" (10:30 ok, 22:00 refused), pickup fee 20 + tax 2 -> total 62, delivery 40 + 200 + 2 tax = 242, blocks 2-6 ("Clifton Blocks 2 to 6", asks "(2 to 6)"), review payment "Card on delivery": PASS');
  // 4) area aliases, receipt wording
  const a2 = sessions.getOrCreateSession().state; run(a2, 'setOrderType', { orderType: 'delivery' }); for (const area of ['Gulshan', 'گلشن اقبال', 'gulshan-e-iqbal']) assert.notStrictEqual(run(a2, 'setCustomerDetails', { area, name: 'Ali' }).error, 'outside_delivery_area'); assert.strictEqual(run(a2, 'setCustomerDetails', { area: 'Clifton' }).error, 'outside_delivery_area');
  const p = await L.post(base, { message: 'hi' }); const sp = sessions.getOrCreateSession(p.json.sessionId).state; run(sp, 'addItemToCart', { itemId: 'NAN01', quantity: 1 }); run(sp, 'setOrderType', { orderType: 'pickup' }); run(sp, 'setCustomerDetails', { name: 'Sami' }); global.__STUB = async ({ contents }) => L.lastToolResults(contents) ? L.text('x') : L.calls([{ name: 'getOrderReview' }], null);
  const c = await L.post(base, { message: 'done', sessionId: p.json.sessionId }); const conf = await fetch(base + '/api/order/confirm', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sessionId: p.json.sessionId, reviewVersion: c.json.reviewVersion }) }).then(r => r.json());
  assert(conf.customerMessage.includes('Payment: cash on pickup. Thank you!') && conf.customerMessage.includes('ادائیگی: پک اپ پر نقد۔'));
  console.log('4) area aliases come from the file (Gulshan / گلشن / gulshan-e-iqbal ok, Clifton refused); the receipt says "Payment: cash on pickup" / "ادائیگی: پک اپ پر نقد۔" built from restaurant.json: PASS');
  // 5) grep checks
  const banned = [/12 noon/, /11 PM/, /\b150\b/, /Blocks? ?\d/, /1–5/, /\bcash\b/i, /Gulshan/, /Karachi/, /Pickup: free/, /23:00/, /12:00/, /daily from/, /on pickup or delivery/];
  for (const re of banned) assert(!re.test(template), 'hardcoded in the prompt file: ' + re);
  const codeFiles = ['checkout.js', 'review.js', 'pricing.js', 'tools.js', 'server.js', 'staff/staff.js']; for (const f of codeFiles) { const src = fs.readFileSync(ROOT + '/backend/' + f, 'utf8').split('\n').filter(l => !l.trim().startsWith('//')).join('\n'); for (const re of [/Gulshan-e-Iqbal/, /\(1 to 5\)/, /Cash on (pickup|delivery)/, /cash on/i, /'Karachi'/]) assert(!re.test(src), `${f} hardcodes ${re}`); }
  const promptOnlyHoursHint = template.match(/\{\{[A-Z_]+\}\}/g); assert(promptOnlyHoursHint.length >= 12);
  console.log('5) grep: prompts/system-prompt.md has no "12 noon", "11 PM", "150", "Blocks 1–5", "cash", "Gulshan", "Karachi", "Pickup: free", "23:00"... (only {{PLACEHOLDERS}}: ' + promptOnlyHoursHint.length + '); the code files hardcode no area name, block range or payment wording: PASS');
  // 6) broken restaurant file -> safe fallback, never a half-filled prompt
  const { Buffer } = require('buffer'); const broken = { ...real }; delete broken.payment;
  await withRestaurant(broken, async () => { global.__STUB = async () => { throw new Error('model must not be called'); }; const r = await L.post(base, { message: 'hello' }); assert.deepStrictEqual([r.status, r.json.reply], [503, 'Please try again or contact staff.']); });
  global.__STUB = async ({ config }) => { lastSys = config.systemInstruction; return L.text('ok'); }; const okAgain = await L.post(base, { message: 'hello' }); assert.strictEqual(okAgain.status, 200);
  const values = JSON.parse(restKeep); assert.deepStrictEqual([values.hours, values.delivery, values.pickup, values.taxRate, values.currency, values.name, values.area, values.city], [{ open: '12:00', close: '23:00' }, { blocks: [1, 2, 3, 4, 5], fee: 150 }, { fee: 0 }, 0, 'PKR', 'Karachi Dastarkhwan', 'Gulshan-e-Iqbal', 'Karachi']);
  console.log('6) a restaurant file missing a required field -> the chat answers the safe 503 fallback and the model is not called; the real values are unchanged (12:00-23:00, blocks 1-5, fee 150, pickup 0, tax 0): PASS');
  console.log('ALL STEP-L TESTS PASSED'); process.exit(0);
})().catch(e => { console.error('TEST FAILED:', e.stack.split('\n').slice(0, 8).join('\n')); process.exit(1); });
