const ROOT = require('path').join(__dirname, '..', '..');
const assert = require('assert'); const fs = require('fs'); const cp = require('child_process');
const git = (args) => cp.spawnSync('git', args, { cwd: ROOT + '/', encoding: 'utf8' }).stdout;
const pkg = JSON.parse(fs.readFileSync(ROOT + '/package.json', 'utf8')); const old = JSON.parse(git(['show', '04491e3:package.json'])); const lock = JSON.parse(fs.readFileSync(ROOT + '/package-lock.json', 'utf8')); const oldLock = JSON.parse(git(['show', '04491e3:package-lock.json']));
assert.deepStrictEqual(pkg.engines, { node: '>=22' }); assert.deepStrictEqual(pkg.dependencies, old.dependencies); assert.deepStrictEqual(pkg.scripts, { start: 'node backend/server.js', test: 'node tests/run-all.js', audit: 'node tests/audit/audit.js', journey: 'node tests/journey/journey.js', 'live-check': 'node scripts/live-check.js' }); assert.strictEqual(pkg.scripts.start, old.scripts.start); assert.deepStrictEqual([pkg.name, pkg.private, pkg.version], [old.name, old.private, old.version]); assert.strictEqual(pkg.devDependencies, undefined);
const { engines: e1, ...restNew } = lock.packages['']; assert.deepStrictEqual(lock.packages[''].engines, { node: '>=22' }); assert.deepStrictEqual(restNew, oldLock.packages['']); const strip = (l) => { const c = JSON.parse(JSON.stringify(l)); delete c.packages[''].engines; return c; }; assert.deepStrictEqual(strip(lock), oldLock);
assert(Number(process.versions.node.split('.')[0]) >= 22);
const readme = fs.readFileSync(ROOT + '/README.md', 'utf8'); assert(readme.includes('Install Node.js 22 or newer (22 is the only version this demo has been tested on)')); assert(!/Node\.js 20/.test(readme));
console.log('package.json engines = {"node": ">=22"}; dependencies, scripts, name, version unchanged; package-lock differs ONLY by the root engines entry (no dependency or version changes); running Node ' + process.versions.node + ' satisfies it; README says Node 22 or newer and no longer claims Node 20: PASS'); console.log('ALL STEP-O TESTS PASSED');
