const ROOT = require('path').join(__dirname, '..', '..');
// Step AF: optional OpenAI-compatible fallback provider (Groq / OpenRouter), tested ONLY against a fake local server
const assert = require('assert'); const fs = require('fs'); const http = require('http'); const cp = require('child_process');
const L = require('./lib.js'); const { sessions, base } = L.boot(3097);
const extraAi = require(ROOT + '/backend/extra-ai'); const cooldown = require(ROOT + '/backend/cooldown'); const { executeTool } = require(ROOT + '/backend/tools');
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const KEY = 'fake-extra-key-do-not-leak-123456'; const requests = []; let behave = () => ({ status: 200, body: { choices: [{ message: { role: 'assistant', content: 'hello from extra' } }] } });
const fake = http.createServer((req, res) => { let b = ''; req.on('data', d => b += d); req.on('end', () => { const json = b ? JSON.parse(b) : null; requests.push({ url: req.url, auth: req.headers.authorization, json });
  const r = behave(json, requests.length); setTimeout(() => { res.writeHead(r.status, { 'Content-Type': 'application/json', ...(r.headers || {}) }); res.end(JSON.stringify(r.body || {})); }, r.delay || 0); }); });
const textMsg = (t) => ({ status: 200, body: { choices: [{ message: { role: 'assistant', content: t } }] } });
const toolMsg = (calls) => ({ status: 200, body: { choices: [{ message: { role: 'assistant', content: null, tool_calls: calls.map((c, i) => ({ id: 'call_' + (i + 1), type: 'function', function: { name: c.name, arguments: typeof c.args === 'string' ? c.args : JSON.stringify(c.args || {}) } })) } }] } });
const lastIsTool = (j) => j.messages[j.messages.length - 1].role === 'tool';
const geminiDown = (status = 429) => { global.__STUB = async () => { throw L.err(status); }; };
const logs = []; const ol = console.log, oe = console.error; console.log = (...a) => { logs.push(a.join(' ')); ol(...a); }; console.error = (...a) => { logs.push(a.join(' ')); oe(...a); };
const ask = async (message, sessionId) => { requests.length = 0; logs.length = 0; const r = await L.post(base, { message, sessionId }); return r; };
function setEnv(url, models, key) { if (arguments.length < 3) key = KEY; const put = (n, v) => { if (v === undefined) delete process.env[n]; else process.env[n] = v; }; put('EXTRA_AI_BASE_URL', url); put('EXTRA_AI_MODELS', models); put('EXTRA_AI_API_KEY', key); }
(async () => { await sleep(400); await new Promise(r => fake.listen(0, '127.0.0.1', r)); const URL_ = `http://127.0.0.1:${fake.address().port}/openai/v1`; process.env.GEMINI_COOLDOWN_SECONDS = '0';
  // 1) disabled unless all three are present and valid
  for (const [u, m, k] of [[undefined, 'a', KEY], [URL_, undefined, KEY], [URL_, 'a', undefined], ['', 'a', KEY], [URL_, '', KEY], [URL_, ' , ,', KEY], [URL_, 'a', '  '], ['http://example.com/v1', 'a', KEY], ['ftp://x/v1', 'a', KEY], ['not a url', 'a', KEY]]) { setEnv(u, m, k); assert.strictEqual(extraAi.config(), null, JSON.stringify([u, m, k])); assert.deepStrictEqual(extraAi.chainEntries(), []); }
  setEnv('https://api.groq.com/openai/v1/', 'm1, m2 ,m1', 'k'); assert.deepStrictEqual(extraAi.config().models, ['m1', 'm2']); assert.strictEqual(extraAi.config().endpoint, 'https://api.groq.com/openai/v1/chat/completions');
  setEnv('https://openrouter.ai/api/v1', 'x/y:free', 'k'); assert.strictEqual(extraAi.config().endpoint, 'https://openrouter.ai/api/v1/chat/completions');
  setEnv(URL_, undefined, KEY); geminiDown(429); let r = await ask('hi'); assert.strictEqual(r.status, 503); assert.strictEqual(requests.length, 0, 'a disabled provider never makes a request');
  setEnv(undefined, undefined, undefined); r = await ask('hi'); assert.strictEqual(r.status, 503); assert(logs.some(l => l === 'Gemini: all models failed'), 'without the provider the log line is the old one');
  console.log('1) provider is OFF unless base URL, key and models are all set and valid (https or localhost only); Groq and OpenRouter URLs both work by env values only; OFF = no request is ever sent and the old behaviour (503 busy) is unchanged: PASS');
  // 2) all Gemini models 429 -> the extra provider answers
  setEnv(URL_, 'model-a,model-b'); geminiDown(429); behave = () => textMsg('hello from extra'); r = await ask('hello there, secret-message-text');
  assert.strictEqual(r.status, 200); assert.strictEqual(r.json.reply, 'hello from extra'); assert.strictEqual(requests.length, 1); assert.strictEqual(requests[0].url, '/openai/v1/chat/completions'); assert.strictEqual(requests[0].auth, 'Bearer ' + KEY);
  const j = requests[0].json; assert.strictEqual(j.model, 'model-a'); assert.strictEqual(j.messages[0].role, 'system'); assert(j.messages[0].content.includes('Dastarkhwan Assistant')); assert.deepStrictEqual(j.messages.slice(-1)[0], { role: 'user', content: 'hello there, secret-message-text' });
  const tools = j.tools; assert(tools.length >= 10 && tools.every(t => t.type === 'function' && t.function.parameters.type === 'object')); const add = tools.find(t => t.function.name === 'addItemToCart'); assert.strictEqual(add.function.parameters.properties.itemId.type, 'string'); assert.strictEqual(add.function.parameters.properties.quantity.type, 'integer'); assert.strictEqual(add.function.parameters.properties.options.type, 'array'); assert.strictEqual(add.function.parameters.properties.options.items.type, 'object'); assert.deepStrictEqual(add.function.parameters.required, ['itemId', 'quantity']);
  const lg = logs.join('\n'); for (const want of ['Gemini attempt 1: model=gemini-3.8-flash status=429', 'Gemini attempt 3: model=gemini-flash-latest status=429', 'Extra AI attempt 4: model=model-a ok', 'Extra AI answered: model=model-a']) assert(lg.includes(want), want);
  for (const bad of [KEY, '127.0.0.1', '/openai/v1', 'secret-message-text', 'Dastarkhwan Assistant']) assert(!lg.includes(bad), 'log must not contain ' + bad);
  console.log('2) all three Gemini models 429 -> the extra provider answers (model-a), Bearer key sent, system prompt + OpenAI tools (lower-case types) sent; logs "Extra AI attempt 4: model=model-a ok" / "Extra AI answered", and never contain the key, URL or message text: PASS');
  // 3) tool calls: validated by the same code
  const a = await L.post(base, { message: 'hi' }); const sid = a.json.sessionId; const st = sessions.getOrCreateSession(sid).state;
  behave = (j2) => lastIsTool(j2) ? textMsg('Added!') : toolMsg([{ name: 'addItemToCart', args: { itemId: 'BRY01', quantity: 2, options: [{ name: 'spice', choice: 'mild' }] } }]);
  r = await ask('2 mild biryani please', sid); assert.strictEqual(r.json.reply, 'Added!'); assert.strictEqual(st.items.length, 1); assert.strictEqual(st.items[0].quantity, 2); assert.strictEqual(requests.length, 2);
  const m2 = requests[1].json.messages; const asst = m2[m2.length - 2], tool = m2[m2.length - 1]; assert.strictEqual(asst.role, 'assistant'); assert.strictEqual(asst.tool_calls[0].function.name, 'addItemToCart'); assert.strictEqual(typeof asst.tool_calls[0].function.arguments, 'string'); assert.strictEqual(tool.role, 'tool'); assert.strictEqual(tool.tool_call_id, asst.tool_calls[0].id); assert.strictEqual(JSON.parse(tool.content).ok, true);
  behave = (j2) => lastIsTool(j2) ? textMsg('Sorry, not possible.') : toolMsg([{ name: 'addItemToCart', args: { itemId: 'PIZZA9', quantity: 1, price: 1 } }, { name: 'addItemToCart', args: { itemId: 'NAN01', quantity: 0 } }]);
  r = await ask('add a pizza', sid); assert.strictEqual(st.items.length, 1, 'invalid item and zero quantity rejected by the same code'); assert.strictEqual(st.items[0].quantity, 2); const rejected = requests[1].json.messages.filter(m => m.role === 'tool').map(m => JSON.parse(m.content)); assert(rejected.length === 2 && rejected.every(x => x.ok === false), 'both calls were answered with a rejection');
  console.log('3) a tool call from the extra provider runs through the same code: valid addItemToCart changes the cart, tool_call_id links the result; unknown item / quantity 0 / injected price are rejected by the code and the model is told: PASS');
  // 4) malformed output = failed attempt, next model, nothing applied, no crash
  const before = JSON.stringify(st.items);
  for (const [name, first] of [['malformed JSON arguments', toolMsg([{ name: 'addItemToCart', args: '{"itemId": "BRY01", quantity' }])], ['unknown tool', toolMsg([{ name: 'deleteEverything', args: {} }])], ['array arguments', toolMsg([{ name: 'addItemToCart', args: '[1,2]' }])], ['empty reply', textMsg('   ')], ['null content, no calls', { status: 200, body: { choices: [{ message: { role: 'assistant', content: null } }] } }], ['no choices', { status: 200, body: {} }], ['not JSON object', { status: 200, body: [] }],
    ['one valid + one invalid call', toolMsg([{ name: 'addItemToCart', args: { itemId: 'NAN01', quantity: 1 } }, { name: 'nope', args: {} }])]]) {
    behave = (j2, n) => (n === 1 ? first : textMsg('second model ok')); r = await ask('x', sid); assert.strictEqual(r.status, 200, name); assert.strictEqual(r.json.reply, 'second model ok', name); assert.strictEqual(requests.length, 2, name); assert.strictEqual(requests[0].json.model, 'model-a'); assert.strictEqual(requests[1].json.model, 'model-b'); assert.strictEqual(JSON.stringify(st.items), before, name + ': nothing applied');
  }
  assert(logs.some(l => /Extra AI attempt \d: model=model-a status=(bad_|unknown_|empty_)/.test(l)), 'the reason keyword is logged');
  behave = () => ({ status: 200, body: { choices: [{ message: { role: 'assistant', content: null, tool_calls: [{ id: 'c', type: 'function', function: { name: 'getMenu', arguments: '' } }] } }] } });
  const ok = extraAi.parseResponse({ choices: [{ message: { tool_calls: [{ id: 'c', type: 'function', function: { name: 'getMenu', arguments: '' } }] } }] }, new Set(['getMenu'])); assert.deepStrictEqual(ok.response.functionCalls, [{ id: 'c', name: 'getMenu', args: {} }]);
  behave = () => textMsg('only'); const both = await ask('y'); assert.strictEqual(both.json.reply, 'only');
  behave = () => ({ status: 500, body: {} }); r = await ask('z'); assert.strictEqual(r.status, 503); assert(logs.some(l => l === 'AI: all models failed')); assert.strictEqual(requests.length, 2);
  console.log('4) malformed JSON args, unknown tool, array args, empty/null reply, bad body, or one bad call among valid ones -> that model fails (reason logged), the next model answers, NOTHING is applied, no crash; both models failing -> normal 503 busy: PASS');
  // 5) cooldown on 429 / 503 / Retry-After, same cooldown mechanism
  process.env.GEMINI_COOLDOWN_SECONDS = '1'; cooldown._reset(); behave = (j2, n) => (j2.model === 'model-a' ? { status: 429, headers: { 'Retry-After': '2' }, body: {} } : textMsg('from b'));
  r = await ask('one'); assert.strictEqual(r.json.reply, 'from b'); assert.deepStrictEqual(requests.map(x => x.json.model), ['model-a', 'model-b']);
  await sleep(1150); r = await ask('two'); assert.deepStrictEqual(requests.map(x => x.json.model), ['model-b'], 'Retry-After 2 s keeps model-a skipped'); assert(logs.some(l => /^Extra AI skip: model=model-a \(cooldown \ds, level 1\)$/.test(l)));
  await sleep(1100); r = await ask('three'); assert.deepStrictEqual(requests.map(x => x.json.model), ['model-a', 'model-b'], 'tried again after the window'); // (its repeated 429 now starts the next level)
  cooldown._reset(); behave = (j2) => (j2.model === 'model-a' ? { status: 503, body: {} } : textMsg('from b')); await ask('x'); r = await ask('y'); assert.deepStrictEqual(requests.map(x => x.json.model), ['model-b']);
  cooldown._reset(); behave = () => ({ status: 500, body: {} }); await ask('x'); r = await ask('y'); assert.deepStrictEqual(requests.map(x => x.json.model), ['model-a', 'model-b'], '500 does not start a cooldown');
  process.env.GEMINI_COOLDOWN_SECONDS = '0'; cooldown._reset();
  console.log('5) an extra model answering 429 (Retry-After 2 honoured over the 1 s default) or 503 is skipped for the cooldown and tried again afterwards; 500 starts no cooldown; skip lines read "Extra AI skip: model=... (cooldown Ns)": PASS');
  // 6) timeout on the same per-attempt limit, via the provider function directly (the server uses the same REQUEST_TIMEOUT_MS)
  behave = () => ({ status: 200, delay: 400, body: { choices: [{ message: { content: 'late' } }] } }); const t0 = Date.now(); const to = await extraAi.attempt('extra:model-a', [{ role: 'user', parts: [{ text: 'hi' }] }], 'sys', [], 100); assert.deepStrictEqual(to, { failure: 'timeout' }); assert(Date.now() - t0 < 350);
  const src = fs.readFileSync(ROOT + '/backend/server.js', 'utf8'); assert(src.includes('REQUEST_TIMEOUT_MS = 20000') && src.includes('TOTAL_DEADLINE_MS = 80000') && src.includes("DEFAULT_MODEL = 'gemini-3.8-flash'") && src.includes("'gemini-3.7-flash,gemini-flash-latest'")); assert(/extraAi\.attempt\(entry, contents, systemInstruction, TOOL_DECLARATIONS, REQUEST_TIMEOUT_MS\)/.test(src));
  console.log('6) the extra provider uses the same 20 s per-attempt limit (timeout -> failure) and the shared 80 s deadline; Gemini names, order and timeouts unchanged: PASS');
  // 7) Gemini 400/403 skips the rest of Gemini but still tries the extra provider; without it the old 502 stays
  geminiDown(403); behave = () => textMsg('extra after 403'); r = await ask('hi'); assert.strictEqual(r.json.reply, 'extra after 403'); assert(logs.some(l => l === 'Gemini attempt 1: model=gemini-3.8-flash status=403') && !logs.some(l => l.includes('model=gemini-3.7-flash')));
  setEnv(undefined, undefined, undefined); r = await ask('hi'); assert.strictEqual(r.status, 502);
  console.log('7) Gemini 403: the other Gemini models are skipped as before, but the extra provider is still tried; with no extra provider the old 502 answer is unchanged: PASS');
  // 8) a whole pickup journey where EVERY reply comes from the extra provider -> saved order; guard + gate unchanged
  setEnv(URL_, 'model-a,model-b'); geminiDown(429); const script = { 'biryani': [{ name: 'addItemToCart', args: { itemId: 'BRY01', quantity: 1, options: [{ name: 'spice', choice: 'mild' }] } }, { name: 'addItemToCart', args: { itemId: 'RAI01', quantity: 1 } }], 'pickup': [{ name: 'setOrderType', args: { orderType: 'pickup' } }], 'name is Hamza': [{ name: 'setCustomerDetails', args: { name: 'Hamza', noPickupTimePreference: true } }], 'review': [{ name: 'getOrderReview' }] };
  let lastUser = ''; behave = (j2) => { if (lastIsTool(j2)) { const tm = j2.messages.filter(m => m.role === 'tool'); return textMsg(JSON.parse(tm[tm.length - 1].content).customerMessage); } lastUser = j2.messages[j2.messages.length - 1].content; const k = Object.keys(script).find(x => lastUser.includes(x)); return k ? toolMsg(script[k]) : textMsg('Is that everything?'); };
  const history = []; let sid2 = null; const say = async (m) => { const x = await L.post(base, { message: m, sessionId: sid2, conversationHistory: history.slice(-10) }); sid2 = x.json.sessionId; history.push({ role: 'user', content: m }, { role: 'assistant', content: x.json.reply }); return x.json; };
  await say('one mild biryani and raita'); await say('pickup'); await say('my name is Hamza'); const rv = await say('review please'); assert(rv.reply.startsWith('Order review') && rv.reply.includes('Total: 430 PKR'), rv.reply); assert.match(rv.reviewVersion, /^[0-9a-f]{16}$/);
  behave = () => textMsg('Your order is confirmed!'); const fakeClaim = await say('ok'); assert(fakeClaim.reply.startsWith('Your order has not been placed yet'), 'guard works for the extra provider too'); assert.strictEqual(JSON.parse(fs.readFileSync(global.__ORDERS_FILE, 'utf8')).length, 0);
  const typed = await fetch(base + '/api/order/confirm', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sessionId: sid2, reviewVersion: 'a'.repeat(16) }) }); assert.strictEqual(typed.status, 409);
  const conf = await fetch(base + '/api/order/confirm', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sessionId: sid2, reviewVersion: rv.reviewVersion }) }); const cj = await conf.json(); assert.strictEqual(conf.status, 200); assert.match(cj.orderId, /^KD-\d+$/);
  const saved = JSON.parse(fs.readFileSync(global.__ORDERS_FILE, 'utf8')); assert.strictEqual(saved.length, 1); assert.strictEqual(saved[0].review.totals.total, 430);
  process.env.ORDERS_ENABLED = 'false'; behave = () => textMsg('hi'); const off = await L.post(base, { message: 'again', sessionId: sid2 }); assert.strictEqual(off.json.reviewVersion, null); process.env.ORDERS_ENABLED = 'true';
  console.log('8) full pickup journey with every reply from the extra provider: review 430 PKR, a fake "order is confirmed" is replaced by the guard, only the button saves (' + cj.orderId + ', total 430), ORDERS_ENABLED off still hides the button: PASS');
  // 9) Gemini key missing but the extra provider configured: the chain is the extra models only (child process, no real network)
  const child = `process.env.NODE_ENV='test'; process.env.PORT='3098'; process.env.GEMINI_API_KEY=''; require('${ROOT}/backend/orders').setOrdersPathForTests(require('os').tmpdir() + '/kd-t47-orders.json'); require('${ROOT}/backend/server'); setTimeout(async () => { const r = await fetch('http://localhost:3098/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: 'hi' }) }); console.log('CHILD ' + r.status + ' ' + (await r.json()).reply); process.exit(0); }, 500);`;
  behave = () => textMsg('extra only'); requests.length = 0; const out = await new Promise(res => { const c = cp.spawn('node', ['-e', child], { cwd: ROOT, env: { ...process.env, GEMINI_API_KEY: '' } }); let s = ''; c.stdout.on('data', d => s += d); c.on('close', () => res(s)); });
  assert(out.includes('CHILD 200 extra only'), out); assert.strictEqual(requests.length, 1);
  console.log('9) no GEMINI_API_KEY but the extra provider set: Gemini is skipped entirely and the extra models answer: PASS');
  console.log = ol; console.error = oe; fake.close(); console.log('ALL STEP-AF TESTS PASSED'); process.exit(0);
})().catch(e => { console.log = ol; console.error = oe; console.error('TEST FAILED:', e.stack.split('\n').slice(0, 10).join('\n')); process.exit(1); });
