const ROOT = require('path').join(__dirname, '..', '..');
// Step AL: valid delivery address forms are accepted (reproduces the live-check S1 step 4 -> 5 sequence with the tool calls a model could send)
const assert = require('assert'); require('./lib.js');
const { executeTool } = require(ROOT + '/backend/tools'); const sessions = require(ROOT + '/backend/sessions'); const { missingDetails, parseBlock } = require(ROOT + '/backend/checkout');
// the S1 sequence up to the refusal: roll with chutney, delivery, "deliver to Gulshan", "Block 9 house 12 Street 4" refused
const afterRefusal = () => { const st = sessions.getOrCreateSession().state; const r = (n, a) => executeTool(n, a, { state: st }); r('addItemToCart', { itemId: 'ROL01', quantity: 1, options: [{ name: 'chutney', choice: 'with' }] }); r('setOrderType', { orderType: 'delivery' }); r('setCustomerDetails', { area: 'Gulshan' });
  const refused = r('setCustomerDetails', { block: '9', houseOrFlat: '12', street: 'Street 4' }); assert.strictEqual(refused.error, 'outside_delivery_area'); assert(!st.customer.address || (!st.customer.address.block && !st.customer.address.house && !st.customer.address.street), 'the refusal stored nothing, not even house 12'); return { st, r }; };
const stored = (st) => { const a = st.customer.address || {}; return [a.block, a.house, a.street]; };
const forms = [
  ['(i) block "3", house "12-B", street "4"', { block: '3', houseOrFlat: '12-B', street: '4' }, [3, '12-B', '4']],
  ['(i) same with street "Street 4"', { block: '3', houseOrFlat: '12-B', street: 'Street 4' }, [3, '12-B', 'Street 4']],
  ['(ii) "Block 3" and "house 12-B"', { block: 'Block 3', houseOrFlat: 'house 12-B', street: 'Street 4' }, [3, '12-B', 'Street 4']],
  ['(ii) "Block-3", "House No. 12-B"', { block: 'Block-3', houseOrFlat: 'House No. 12-B', street: 'Street 4' }, [3, '12-B', 'Street 4']],
  ['(ii) "بلاک 3", "Flat 12-B"', { block: 'بلاک 3', houseOrFlat: 'Flat 12-B', street: 'Street 4' }, [3, '12-B', 'Street 4']],
  ['(iii) one combined address string', { address: 'Block 3, house 12-B, Street 4' }, [3, '12-B', 'Street 4']],
  ['(iii) combined with area and city', { address: 'House 12-B, Street 4, Block 3, Gulshan-e-Iqbal, Karachi' }, [3, '12-B', 'Street 4']],
  ['(iii) combined, street named "Main Rashid Minhas Road"', { address: 'Flat 4, Main Rashid Minhas Road, Block 5' }, [5, '4', 'Main Rashid Minhas Road']],
  ['(iii) combined plus area field', { area: 'Gulshan', address: 'blk 3, house 12-B, st 4' }, [3, '12-B', 'st 4']],
  ['numbers instead of strings (house 12, street 4)', { block: 3, houseOrFlat: 12, street: 4 }, [3, '12', '4']],
  ['all numbers with a text house', { block: 3, houseOrFlat: '12-B', street: 4 }, [3, '12-B', '4']],
  ['empty / null extras next to valid fields', { block: '3', houseOrFlat: '12-B', street: 'Street 4', apartment: null, landmark: '', instructions: null, phone: null, name: null }, [3, '12-B', 'Street 4']],
  ['area given as "Block 3, Gulshan-e-Iqbal" plus parts', { area: 'Block 3, Gulshan-e-Iqbal', block: '3', houseOrFlat: '12-B', street: 'Street 4' }, [3, '12-B', 'Street 4']],
  ['separate fields win over the combined text', { address: 'Block 5, house 99, Street 9', block: '3', houseOrFlat: '12-B', street: 'Street 4' }, [3, '12-B', 'Street 4']]
];
for (const [name, args, want] of forms) { const { st, r } = afterRefusal(); const x = r('setCustomerDetails', args); assert.strictEqual(x.ok, true, name + ' -> ' + JSON.stringify(x)); assert.deepStrictEqual(stored(st), want, name); assert(!missingDetails(st).some((m) => ['block', 'house', 'street'].includes(m.field)), name + ': block, house and street are all present'); assert.strictEqual(st.orderType, 'delivery'); }
console.log(`1) after the Block 9 refusal ${forms.length} valid forms are stored correctly (block 3, house 12-B, street 4): strings, "Block 3"/"Block-3"/"بلاک 3", "house 12-B"/"House No. 12-B"/"Flat 12-B" (label word removed), JSON numbers, empty/null extras, and one combined labelled address text: PASS`);
// the read-back shows clean text
{ const { st, r } = afterRefusal(); r('setCustomerDetails', { address: 'Block 3, house 12-B, Street 4' }); r('setCustomerDetails', { name: 'Ali', phone: '03211234567', noExtraAddressDetails: true }); const rb = r('readBackAddress', {}); assert.strictEqual(rb.ok, true); assert(rb.customerMessage.includes('House or flat 12-B, Street 4, Block 3'), rb.customerMessage); }
// still refused, never guessed. Step BB: every field is judged on its own, so a bad part is left out and reported while the good parts are kept
// (an address outside the area is the exception: no part of it is kept). tuple: [name, args, error, kept [block, house, street] (null = nothing kept)]
for (const [name, args, err, kept] of [['combined text with Block 9', { address: 'Block 9, house 12, Street 4' }, 'outside_delivery_area', null], ['combined text with block 0', { address: 'Block 0, house 12, Street 4' }, 'invalid_block', [undefined, '12', 'Street 4']], ['unlabelled part', { address: 'Block 3, 12-B, Street 4' }, 'invalid_address', null], ['only a landmark text', { address: 'near Imtiaz store' }, 'invalid_address', null], ['two blocks', { address: 'Block 3, Block 4, house 1, Street 2' }, 'invalid_address', null], ['all in one segment', { address: 'Block 3 house 12-B Street 4' }, 'invalid_address', null], ['outside area name', { address: 'Clifton, Block 3, house 1, Street 2' }, 'invalid_address', null], ['bad house characters', { address: 'Block 3, house <script>, Street 4' }, 'invalid_address', [3, undefined, 'Street 4']], ['too long', { address: 'Block 3, house 1, ' + 'x'.repeat(300) }, 'invalid_address', null], ['negative number', { block: '3', houseOrFlat: -12, street: 'Street 4' }, 'invalid_address', [3, undefined, 'Street 4']], ['decimal number', { block: '3', houseOrFlat: 12.5, street: 'Street 4' }, 'invalid_address', [3, undefined, 'Street 4']], ['object', { block: '3', houseOrFlat: { n: 12 }, street: 'Street 4' }, 'invalid_address', [3, undefined, 'Street 4']]]) {
  const { st, r } = afterRefusal(); const x = r('setCustomerDetails', args); const a = st.customer.address || {};
  if (kept === null) { assert.strictEqual(x.ok, false, name); assert.strictEqual(x.error, err, name + ' -> ' + x.error); assert(!a.block && !a.house && !a.street, name + ': nothing stored'); }
  else { assert.strictEqual(x.ok, true, name); assert(x.rejectedFields.some((f) => f.error === err), name); assert.deepStrictEqual([a.block || undefined, a.house || undefined, a.street || undefined], kept, name + ': the valid parts are kept, the bad one is not'); } }
{ const { st, r } = afterRefusal(); const x = r('setCustomerDetails', { address: 'Block 3, house 12-B, Street 4' }); assert.strictEqual(x.ok, true); r('setCustomerDetails', { name: 'Ali', phone: '03211234567' }); r('readBackAddress', {}); r('confirmAddress', {}, 'yes'); }
console.log('2) never guessed: Block 9 inside a combined text (no part kept), unlabelled or double parts, a landmark only, other areas, odd characters and over-long text (nothing kept), and block 0 / negative / decimal / object values (only the bad field left out, the good ones kept and the bad one reported): PASS');
// pickup ignores addresses; a valid address after a refusal still goes through the normal confirm flow
{ const st = sessions.getOrCreateSession().state; const r = (n, a, m) => executeTool(n, a, { state: st, latestMessage: m }); r('addItemToCart', { itemId: 'NAN01', quantity: 1 }); r('setOrderType', { orderType: 'pickup' }); const x = r('setCustomerDetails', { name: 'Ali', address: 'Block 3, house 12-B, Street 4' }); assert.strictEqual(x.ok, true); assert(!st.customer.address || !st.customer.address.block, 'pickup never stores an address'); }
{ const { st, r } = afterRefusal(); r('setCustomerDetails', { address: 'Block 3, house 12-B, Street 4' }); r('setCustomerDetails', { name: 'Ali', phone: '03211234567', noExtraAddressDetails: true }); r('readBackAddress', {}); assert.strictEqual(executeTool('confirmAddress', {}, { state: st, latestMessage: 'ok' }).ok, false); assert.strictEqual(executeTool('confirmAddress', {}, { state: st, latestMessage: 'haan, sahi hai' }).ok, true); const rv = r('getOrderReview', {}); assert(rv.ok && rv.review.totals.total === 370, 'review 370'); }
assert.strictEqual(parseBlock('Block 3'), 3);
console.log('3) pickup still ignores an address; the S1 flow after the refusal (address, phone, read-back, "ok" refused, "haan, sahi hai" accepted, review 370 PKR) works with the combined form too: PASS'); console.log('ALL STEP-AL TESTS PASSED'); process.exit(0);
