const ROOT = require('path').join(__dirname, '..', '..');
// Step AQ: the read-back comes together with the optional extras question (never a separate turn before it)
const assert = require('assert'); const fs = require('fs'); const L = require('./lib.js'); const { sessions, base } = L.boot(3103);
const { executeTool } = require(ROOT + '/backend/tools');
const EXTRAS_Q = 'Optional: is there an apartment or unit number, or any delivery instructions? (You can say no.)'; const CONFIRM_Q = 'Is this correct? Please say yes, or tell me what to change.';
const mk = () => { const st = sessions.getOrCreateSession().state; const r = (n, a, m) => executeTool(n, a, { state: st, latestMessage: m }); r('addItemToCart', { itemId: 'ROL01', quantity: 1, options: [{ name: 'chutney', choice: 'with' }] }); r('setOrderType', { orderType: 'delivery' }); return { st, r }; };
// 1) the last required detail: no separate extras question, an instruction to read back in the same turn
let { st, r } = mk(); r('setCustomerDetails', { block: '3', houseOrFlat: '12-B', street: 'Street 4' }); r('setCustomerDetails', { phone: '03211234567' });
let x = r('setCustomerDetails', { name: 'Ali' }); assert.strictEqual(x.ok, true); assert.deepStrictEqual(x.missingDetails, []); assert(!/apartment|instructions/i.test(x.customerMessage), x.customerMessage); assert.strictEqual(x.customerMessage, 'Thanks, Ali.'); assert(x.internalNote.includes('Call readBackAddress now, in this same turn') && x.internalNote.includes('Do not ask the optional question separately'));
// 2) the read-back carries BOTH questions in one message; asked only once
let rb = r('readBackAddress', {}); assert.strictEqual(rb.ok, true); const lines = rb.customerMessage.split('\n'); assert.strictEqual(lines[lines.length - 2], EXTRAS_Q); assert.strictEqual(lines[lines.length - 1], CONFIRM_Q); assert.strictEqual(lines[0], 'Please check your delivery details:'); assert(rb.internalNote.includes('including the optional question and the confirmation question, all in this one reply'));
assert.strictEqual(st.addressReadBack, true); assert.strictEqual(st.addressConfirmed, false);
// 3) "ok" alone is still not a yes; the customer adds apartment + instructions -> store, read back again (extras question not repeated), confirm
assert.strictEqual(r('confirmAddress', {}, 'ok').ok, false); assert.strictEqual(st.addressConfirmed, false);
x = r('setCustomerDetails', { apartment: 'Flat 2', instructions: 'ring twice' }); assert.strictEqual(x.ok, true); assert.strictEqual(st.addressReadBack, false, 'a change needs a fresh read-back'); assert(x.internalNote.includes('Call readBackAddress now'));
rb = r('readBackAddress', {}); assert(rb.customerMessage.includes('Apartment or unit: Flat 2') && rb.customerMessage.includes('Delivery instructions: ring twice')); assert(!rb.customerMessage.includes('Optional:'), 'the optional question is asked once'); assert(rb.customerMessage.endsWith(CONFIRM_Q));
assert.strictEqual(r('confirmAddress', {}, 'theek hai').ok, false); assert.strictEqual(r('confirmAddress', {}, 'haan, sahi hai').ok, true); assert.strictEqual(st.addressConfirmed, true); const rv = r('getOrderReview', {}); assert(rv.ok && rv.review.totals.total === 370);
console.log('3) all required details stored -> "Thanks, Ali." plus an instruction to read back in the same turn (no separate extras question); the read-back message ends with the optional question and then the confirmation question; "ok"/"theek hai" are not a yes; adding apartment + instructions -> new read-back without repeating the optional question; "haan, sahi hai" confirms; review 370: PASS');
// 4) customer already said "no extras" -> read-back without the optional question; pickup flow unchanged
({ st, r } = mk()); r('setCustomerDetails', { name: 'Ali', phone: '03211234567', block: '3', houseOrFlat: '12-B', street: 'Street 4', noExtraAddressDetails: true }); rb = r('readBackAddress', {}); assert(!rb.customerMessage.includes('Optional:') && rb.customerMessage.endsWith(CONFIRM_Q));
({ st, r } = mk()); r('setCustomerDetails', { name: 'Ali', phone: '03211234567', block: '3', houseOrFlat: '12-B', street: 'Street 4', apartment: 'A', instructions: 'B' }); rb = r('readBackAddress', {}); assert(!rb.customerMessage.includes('Optional:'), 'apartment and instructions already given');
{ const p = sessions.getOrCreateSession().state; const rp = (n, a) => executeTool(n, a, { state: p }); rp('addItemToCart', { itemId: 'NAN01', quantity: 1 }); rp('setOrderType', { orderType: 'pickup' }); const y = rp('setCustomerDetails', { name: 'Ali' }); assert(y.customerMessage.includes('Would you like to set a pickup time'), 'the pickup-time question is unchanged'); }
// 5) the prompt carries the rule, and a whole chat turn (stub model: stores the name, reads back) gives ONE reply with all of it
const prompt = fs.readFileSync(ROOT + '/prompts/system-prompt.md', 'utf8'); for (const t of ['as soon as ALL required delivery details are stored', 'in that same turn', 'AND the question to confirm the address', 'never ask the optional question as a separate turn before the read-back', 'store them with setCustomerDetails, call readBackAddress again and ask them to confirm', 'Messages like "ok"']) assert(prompt.includes(t), t);
global.__STUB = async ({ contents }) => { const res = L.lastToolResults(contents); if (res) return L.text(res[res.length - 1].response.customerMessage); return L.calls([{ name: 'setCustomerDetails', args: { name: 'Ali' } }, { name: 'readBackAddress' }], null); };
(async () => { await new Promise(r => setTimeout(r, 400)); const a = await L.post(base, { message: 'hi' }); const s2 = sessions.getOrCreateSession(a.json.sessionId).state; const q = (n, args) => executeTool(n, args, { state: s2 }); q('addItemToCart', { itemId: 'ROL01', quantity: 1, options: [{ name: 'chutney', choice: 'with' }] }); q('setOrderType', { orderType: 'delivery' }); q('setCustomerDetails', { phone: '03211234567', block: '3', houseOrFlat: '12-B', street: 'Street 4' });
  const resp = await L.post(base, { message: 'Ali', sessionId: a.json.sessionId }); assert(resp.json.reply.includes('Name: Ali') && resp.json.reply.includes(EXTRAS_Q) && resp.json.reply.endsWith(CONFIRM_Q), resp.json.reply); assert.strictEqual(s2.addressReadBack, true);
  console.log('4) "no extras" or apartment + instructions already given -> no optional question; pickup-time question unchanged; the prompt has the rule; one chat turn (name stored + readBackAddress) returns ONE reply with details, the optional question and the confirmation question: PASS'); console.log('ALL STEP-AQ TESTS PASSED'); process.exit(0); })().catch(e => { console.error('TEST FAILED:', e.stack.split('\n').slice(0, 8).join('\n')); process.exit(1); });
