const ROOT = require('path').join(__dirname, '..', '..');
// Step AS: encrypted client-held session state (Vercel-safe): two separate instances share one cart through the token
const assert = require('assert'); const fs = require('fs'); const os = require('os'); const path = require('path'); const cp = require('child_process');
const SECRET = 'unit-test-secret-0123456789-abcdefghijklmnopqrstuvwxyz'; const OTHER = 'a-different-unit-test-secret-9876543210-zyxwvutsrqponmlk';
process.env.NODE_ENV = 'test'; process.env.SESSION_SECRET = SECRET; delete process.env.VERCEL;
const tk = require(ROOT + '/backend/session-token'); const sessions = require(ROOT + '/backend/sessions');
const sid = 'ab'.repeat(16); const state = { items: [{ lineId: 'L1', id: 'BRY01', name: 'Chicken Biryani', quantity: 2, options: { spice: 'mild' } }], customer: { name: 'Hamza Ali', phone: null, address: null }, orderType: 'pickup', status: 'draft', reviewShownVersion: null, totals: { total: 700 } };
// ---- 1) the token itself ----
const t = tk.seal(sid, state); assert.strictEqual(typeof t, 'string'); assert(/^[A-Za-z0-9_-]+$/.test(t)); const o = tk.open(t); assert.deepStrictEqual(o, { sessionId: sid, state });
const raw = Buffer.from(t, 'base64url'); for (const secretText of ['Hamza', 'BRY01', 'Biryani', 'pickup', sid]) assert(!raw.toString('latin1').includes(secretText) && !t.includes(secretText), 'the state is encrypted: ' + secretText); assert(t.length < 1200, 'small token: ' + t.length);
assert.notStrictEqual(tk.seal(sid, state), t, 'a fresh random IV every time');
let bad = 0; for (let i = 0; i < t.length; i += 7) { const c = t[i] === 'A' ? 'B' : 'A'; assert.strictEqual(tk.open(t.slice(0, i) + c + t.slice(i + 1)), null, 'tampered at ' + i); bad += 1; }
for (const x of [t.slice(0, -2), t + 'AA', t.slice(1), '', 'x', 'a'.repeat(100), t + '!', null, undefined, 42, {}, [], 'a'.repeat(70000)]) assert.strictEqual(tk.open(x), null, String(x).slice(0, 20));
assert(tk.open(t, Date.now() + tk.MAX_AGE_MS - 1000) !== null, 'valid just before 2 hours'); assert.strictEqual(tk.open(t, Date.now() + tk.MAX_AGE_MS + 1000), null, 'expired after 2 hours'); assert.strictEqual(tk.open(tk.seal(sid, state, Date.now() - 3 * 3600 * 1000)), null, 'old token'); assert.strictEqual(tk.open(tk.seal(sid, state, Date.now() + 3600 * 1000)), null, 'token from the future');
process.env.SESSION_SECRET = OTHER; assert.strictEqual(tk.open(t), null, 'another secret cannot open it'); const t2 = tk.seal(sid, state); process.env.SESSION_SECRET = SECRET; assert.strictEqual(tk.open(t2), null);
assert.strictEqual(tk.open(tk.seal('not-a-session-id', state)), null); assert.strictEqual(tk.open(tk.seal(sid, [1, 2])), null);
// a token whose state lacks / mistypes fields is repaired on adoption (unknown or wrong-kind fields are dropped)
const adopted = sessions.adoptSession(sid, { items: 'nope', bogus: 1, orderType: 'delivery', customer: { name: 'A', phone: null, address: null } }); assert.deepStrictEqual(adopted.state.items, [], 'a wrong-kind items value is dropped (empty cart)'); assert.strictEqual(adopted.state.orderType, 'delivery'); assert.strictEqual(adopted.state.bogus, undefined);
const ok = sessions.adoptSession(sid, { ...state, bogus: 1, confirmed: 'yes' }); assert.strictEqual(ok.state.bogus, undefined); assert.strictEqual(ok.state.confirmed, false, 'wrong kind dropped'); assert.strictEqual(ok.state.items[0].quantity, 2); assert.deepStrictEqual(sessions.getExistingSession(sid).state, ok.state);
console.log(`1) token: AES-256-GCM round trip; the state is not readable in it; ${bad} single-character changes, truncation, padding, wrong types, 70 kB junk, another secret, expiry (2 h), future time, bad session id: all -> null, never an exception; ~${t.length} characters for a cart; adoption keeps only known fields of the right kind: PASS`);
// ---- 2) two real instances (separate processes) with the same secret ----
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'kd-t59-'));
const childCode = `process.env.NODE_ENV='test'; const L = require('${ROOT}/tests/unit/lib.js'); const fs = require('fs');
require('${ROOT}/backend/orders').setOrdersPathForTests(process.env.T59_ORDERS); fs.writeFileSync(process.env.T59_ORDERS, '[]');
global.__STUB = async ({ contents }) => { const last = contents[contents.length - 1]; const res = last.parts.filter(p => p.functionResponse).map(p => p.functionResponse.response); if (res.length) return L.text(res[res.length - 1].customerMessage);
  const said = last.parts.map(p => p.text || '').join(' '); const S = { 'add naan': [{ name: 'addItemToCart', args: { itemId: 'NAN01', quantity: 1 } }], 'pickup': [{ name: 'setOrderType', args: { orderType: 'pickup' } }], 'my name': [{ name: 'setCustomerDetails', args: { name: 'Ali', noPickupTimePreference: true } }], 'review': [{ name: 'getOrderReview' }], 'cart': [{ name: 'viewCart' }] };
  const k = Object.keys(S).find(x => said.includes(x)); return k ? L.calls(S[k], null) : L.text('hello'); };
const app = require('${ROOT}/backend/server'); if (process.env.VERCEL) require('http').createServer(app).listen(Number(process.env.PORT));`;
const children = []; const start = (port, env) => new Promise((resolve) => { const orders = path.join(tmp, `orders-${port}.json`); const c = cp.spawn('node', ['-r', ROOT + '/tests/unit/stub.js', '-e', childCode], { cwd: ROOT, env: { ...process.env, PORT: String(port), GEMINI_API_KEY: 'stub-not-a-real-key', ORDERS_ENABLED: 'true', T59_ORDERS: orders, GEMINI_COOLDOWN_SECONDS: '0', ...env }, stdio: ["ignore", "pipe", "pipe"] }); let log = ''; c.stdout.on('data', d => log += d); c.stderr.on('data', d => log += d); children.push(c);
  (async () => { for (let i = 0; i < 60; i += 1) { try { const r = await fetch(`http://localhost:${port}/`); if (r.status === 200) break; } catch (e) { /* not up yet */ } await new Promise(r => setTimeout(r, 100)); } resolve({ port, orders, log: () => log }); })(); });
const post = async (inst, p, body) => { const r = await fetch(`http://localhost:${inst.port}${p}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); return { status: r.status, json: await r.json() }; };
(async () => {
  const env = { SESSION_SECRET: SECRET }; delete env.VERCEL; const A = await start(3111, env); const B = await start(3112, env); const C = await start(3113, { SESSION_SECRET: OTHER });
  let tok = null; let id = null; const say = async (inst, message) => { const r = await post(inst, '/api/chat', { message, sessionId: id, sessionToken: tok }); assert.strictEqual(r.status, 200, JSON.stringify(r.json) + '\nLOG: ' + inst.log().slice(-600)); tok = r.json.sessionToken; id = r.json.sessionId; assert.strictEqual(typeof tok, 'string'); return r.json; };
  await say(A, 'add naan'); await say(B, 'add naan'); await say(A, 'pickup'); await say(B, 'my name is Ali'); let c = await say(A, 'show cart'); assert(c.reply.includes('2 x Naan') || c.reply.includes('Naan'), c.reply); assert(/80 PKR/.test(c.reply) || c.reply.includes('Total: 80'), 'two naan = 80 PKR: ' + c.reply);
  const rv = await say(B, 'review please'); assert.match(rv.reviewVersion, /^[0-9a-f]{16}$/); assert(rv.reply.includes('2 x Naan - 80 PKR') && rv.reply.includes('Name: Ali') && rv.reply.includes('Total: 80 PKR'), rv.reply);
  assert.strictEqual(JSON.parse(fs.readFileSync(A.orders, 'utf8')).length + JSON.parse(fs.readFileSync(B.orders, 'utf8')).length, 0);
  const idBefore = id; const tokBefore = tok;
  // the confirm goes to the OTHER instance than the one that showed the review: it only has the token
  const noToken = await post(A, '/api/order/confirm', { sessionId: id, reviewVersion: rv.reviewVersion }); assert.strictEqual(noToken.status, 409, 'control: instance A only has its own older memory of the session (no review was shown there), so a token-less confirm there is refused'); assert.strictEqual(noToken.json.error, 'review_not_shown');
  const conf = await post(B, '/api/order/confirm', { sessionId: id, sessionToken: tokBefore, reviewVersion: rv.reviewVersion }); assert.strictEqual(conf.status, 200, JSON.stringify(conf.json)); assert.match(conf.json.orderId, /^KD-\d+$/); assert.strictEqual(typeof conf.json.sessionToken, 'string');
  const savedB = JSON.parse(fs.readFileSync(B.orders, 'utf8')); assert.strictEqual(savedB.length, 1); assert.strictEqual(savedB[0].review.totals.total, 80); assert.strictEqual(savedB[0].review.customer.name, 'Ali');
  const after = await post(A, '/api/chat', { message: 'show cart', sessionId: id, sessionToken: conf.json.sessionToken }); assert.strictEqual(after.status, 200);
  console.log('2) two separate server processes with the same SESSION_SECRET: add naan (A), add naan (B), pickup (A), name (B), cart (A) shows 2 naan = 80 PKR, review on B, confirm on B using only the token -> saved ' + conf.json.orderId + ' (80 PKR, Ali), and a token-less confirm on the instance that only has an older memory copy is refused (review_not_shown): PASS');
  // ---- 3) invalid tokens start a fresh empty session ----
  const fresh = async (inst, token, label) => { const r = await post(inst, '/api/chat', { message: 'show cart', sessionId: idBefore, sessionToken: token }); assert.strictEqual(r.status, 200, label); assert.notStrictEqual(r.json.sessionId, idBefore, label + ': a new session id'); assert(/empty|nothing|no items/i.test(r.json.reply) || !r.json.reply.includes('Naan'), label + ': empty cart: ' + r.json.reply); assert.strictEqual(r.json.reviewVersion, null); return r.json; };
  const flipped = tokBefore.slice(0, 30) + (tokBefore[30] === 'A' ? 'B' : 'A') + tokBefore.slice(31); await fresh(B, flipped, 'tampered'); await fresh(B, tokBefore.slice(0, -4), 'truncated'); await fresh(B, 'garbage-token-garbage-token-garbage-token-garbage', 'garbage');
  const oldTok = tk.seal(idBefore, state, Date.now() - 3 * 3600 * 1000); await fresh(B, oldTok, 'expired'); await fresh(C, tokBefore, 'other secret'); const cfNew = await post(C, '/api/order/confirm', { sessionId: idBefore, sessionToken: tokBefore, reviewVersion: rv.reviewVersion }); assert.strictEqual(cfNew.status, 404); assert.strictEqual(cfNew.json.error, 'session_not_found');
  const cfBad = await post(B, '/api/order/confirm', { sessionId: idBefore, sessionToken: flipped, reviewVersion: rv.reviewVersion }); assert.strictEqual(cfBad.status, 404); assert.strictEqual(JSON.parse(fs.readFileSync(B.orders, 'utf8')).length, 1, 'no second order');
  const cfPlain = await post(C, '/api/order/confirm', { sessionId: idBefore, reviewVersion: rv.reviewVersion }); assert.strictEqual(cfPlain.status, 404, 'a bare session id means nothing on an instance that never saw it');
  console.log('3) tampered, truncated, garbage, expired (3 h old) and other-secret tokens all give a fresh empty session (new id, no review) and never an error; a bad token on confirm -> 404 session_not_found and nothing is saved; a plain session id alone is worthless on another instance: PASS');
  // ---- 4) Vercel without a secret fails closed; local without a secret generates one ----
  const V = await start(3114, { VERCEL: '1', SESSION_SECRET: '' }); const vr = await post(V, '/api/chat', { message: 'hi' }); assert.strictEqual(vr.status, 503); assert.strictEqual(vr.json.error, 'session_not_configured'); assert(vr.json.reply.includes('not set up correctly')); assert(!('sessionToken' in vr.json));
  const vc = await post(V, '/api/order/confirm', { sessionId: sid, reviewVersion: 'a'.repeat(16) }); assert.strictEqual(vc.status, 503); assert.strictEqual(vc.json.error, 'session_not_configured');
  const V2 = await start(3115, { VERCEL: '1', SESSION_SECRET: 'too-short' }); assert.strictEqual((await post(V2, '/api/chat', { message: 'hi' })).json.error, 'session_not_configured'); const V3 = await start(3116, { VERCEL: '1', SESSION_SECRET: SECRET }); assert.strictEqual((await post(V3, '/api/chat', { message: 'hi' })).status, 200);
  const V4 = await start(3117, { VERCEL: '1', SESSION_SECRET: '', ORDERS_ENABLED: '' }); assert.strictEqual((await post(V4, '/api/order/confirm', { sessionId: sid, reviewVersion: 'a'.repeat(16) })).json.error, 'ordering_disabled', 'the ordering switch is still checked first');
  const Lc = await start(3118, { SESSION_SECRET: '' }); assert(Lc.log().includes('Session secret: generated for this process (set SESSION_SECRET for multi-instance)'), Lc.log()); let t3 = null, i3 = null; for (const m of ['add naan', 'add naan']) { const r = await post(Lc, '/api/chat', { message: m, sessionId: i3, sessionToken: t3 }); t3 = r.json.sessionToken; i3 = r.json.sessionId; assert.strictEqual(r.status, 200); } const cc = await post(Lc, '/api/chat', { message: 'show cart', sessionId: i3, sessionToken: t3 }); assert(cc.json.reply.includes('2 x Naan') || /Naan/.test(cc.json.reply));
  for (const inst of [A, B, C, V, V2, V3, V4, Lc]) for (const bad of [SECRET, OTHER, tokBefore, conf.json.sessionToken]) assert(!inst.log().includes(bad), 'the secret or a token must never be logged');
  console.log('4) VERCEL=1 without SESSION_SECRET (or a too-short one): chat and confirm answer 503 session_not_configured (ordering switch still checked first), with a valid secret it works; locally without a secret one is generated (one log line) and carts work; no log line ever contains a secret or a token: PASS');
  for (const c2 of children) c2.kill(); fs.rmSync(tmp, { recursive: true, force: true }); console.log('ALL STEP-AS TESTS PASSED'); process.exit(0);
})().catch(e => { for (const c2 of children) c2.kill(); console.error('TEST FAILED:', e.stack.split('\n').slice(0, 9).join('\n')); process.exit(1); });
