const ROOT = require('path').join(__dirname, '..', '..');
// Step AV: area / item / address words are never accepted as the customer's name
const assert = require('assert'); const fs = require('fs'); require('./lib.js');
const { executeTool } = require(ROOT + '/backend/tools'); const sessions = require(ROOT + '/backend/sessions');
const fresh = (type) => { const st = sessions.getOrCreateSession().state; executeTool('addItemToCart', { itemId: 'NAN01', quantity: 1 }, { state: st }); executeTool('setOrderType', { orderType: type || 'delivery' }, { state: st }); return st; };
const name = (st, n, extra) => executeTool('setCustomerDetails', { name: n, ...(extra || {}) }, { state: st });
const REJECT = ['Gulshan', 'gulshan', 'GULSHAN', ' Gulshan ', 'گلشن', 'گلشن اقبال', 'Gulshan-e-Iqbal', 'gulshan e iqbal', 'Gulshane Iqbal', 'Gulshan Iqbal', 'گلشنِ اقبال', 'Karachi', 'کراچی', 'Block 3', 'block', 'Blk 3', 'بلاک 3', 'House 12', 'Flat', 'Street 4', 'Road',
  'Chicken Roll', 'chicken roll', 'Chicken Biryani', 'Beef Pulao', 'Daal Chawal', 'Raita', 'Salad', 'Water 500 ml', 'Kheer cup', 'Naan', 'Tea', 'chicken', 'ROL01', 'bry01', 'NAN01', 'Roll Naan', 'pickup', 'Pick up', 'pick-up', 'Delivery', 'ڈیلیوری', 'پک اپ', 'customer', 'Guest', 'unknown', 'N/A', 'n a', 'none', 'Anonymous', 'name', 'گاہک', 'نامعلوم', '12345', '00 11', 'Gulshan Karachi', 'Gulshan Block 3', 'Order'];
const ACCEPT = ['Ali', 'Hamza', 'علی', 'Sarwar Ali', 'Iqbal', 'Muhammad Iqbal', 'Ayesha Khan', "O'Brien", 'Anne-Marie', 'احمد رضا', 'Sara K.', 'Roll Ahmed', 'Tea Ali', 'Hamza Gulshan', 'Karachi Khan', 'Block Ali'];
for (const n of REJECT) { const st = fresh(); const r = name(st, n); assert.strictEqual(r.ok, false, `"${n}" must be rejected`); assert.strictEqual(r.error, 'invalid_name', n); assert.strictEqual(st.customer.name, null, `nothing stored for "${n}"`); assert(r.customerMessage.includes("didn't catch that name"), r.customerMessage); assert(r.internalNote.includes('Do not make up a name: ask for it')); }
for (const n of ACCEPT) { const st = fresh(); const r = name(st, n); assert.strictEqual(r.ok, true, `"${n}" must be accepted: ` + JSON.stringify(r)); assert.strictEqual(st.customer.name, n.replace(/\s+/g, ' ').trim()); }
console.log(`1) ${REJECT.length} non-names rejected with INVALID_NAME and nothing stored (Gulshan / گلشن / Gulshan-e-Iqbal variants, Karachi, Block 3, House 12, Chicken Roll and every menu name or id, pickup, delivery, customer, guest, unknown, N/A, digits, ...); ${ACCEPT.length} real names accepted (Ali, Hamza, علی, Sarwar Ali, Iqbal, Muhammad Iqbal, Roll Ahmed, Hamza Gulshan, ...): PASS`);
// the live failure: area name sent together with the phone must not store a name, and the rest of the call is NOT stored either (atomic)
{ const st = fresh(); const r = name(st, 'Gulshan', { phone: '03211234567', block: '3', houseOrFlat: '12-B', street: 'Street 4' }); assert.strictEqual(r.ok, true, 'Step BB: the invalid name no longer drops the rest'); assert.strictEqual(st.customer.name, null); assert.strictEqual(st.customer.phone, '03211234567'); assert.deepStrictEqual([st.customer.address.block, st.customer.address.house, st.customer.address.street], [3, '12-B', 'Street 4']); assert(r.rejectedFields.some((f) => f.field === 'name' && f.error === 'invalid_name')); assert(r.internalNote.includes('name_not_stored: the customer has not given a name - ask for it; never invent one')); assert(r.missingDetails.some(m => m.field === 'name')); const rb = executeTool('readBackAddress', {}, { state: st }); assert.strictEqual(rb.ok, false); assert.strictEqual(rb.error, 'details_incomplete'); assert(rb.customerMessage.includes('name')); executeTool('setCustomerDetails', { name: 'Ali' }, { state: st }); const rb2 = executeTool('readBackAddress', {}, { state: st }); assert(rb2.customerMessage.includes('Name: Ali')); }
{ const st = fresh('pickup'); assert.strictEqual(name(st, 'Pickup').ok, false); assert.strictEqual(name(st, 'Hamza').ok, true); assert.strictEqual(name(st, 'Naan').ok, false); assert.strictEqual(st.customer.name, 'Hamza', 'a refused change keeps the stored name'); }
const prompt = fs.readFileSync(ROOT + '/prompts/system-prompt.md', 'utf8'); for (const t of ['Names: store a name ONLY from the customer\'s own words saying their name', 'Never derive a name from an area, an address, an item, an order type or any earlier unrelated text', 'never fill in a name just so that you can read the details back: if the name is missing, ask for it']) assert(prompt.includes(t), t);
console.log('2) the live case: area name sent with the phone and address -> the name alone is dropped, phone and address are kept, the name is still asked for, read-back refuses (details_incomplete) until a real name is given; a refused change keeps the stored name; the prompt has the rule: PASS'); console.log('ALL STEP-AV TESTS PASSED');
