const ROOT = require('path').join(__dirname, '..', '..');
// Step AW: after the address is confirmed the reply continues from the real cart
const assert = require('assert'); const fs = require('fs'); const L = require('./lib.js'); const { sessions, base } = L.boot(3104);
const { executeTool } = require(ROOT + '/backend/tools');
const mk = (items) => { const st = sessions.getOrCreateSession().state; const r = (n, a, m) => executeTool(n, a, { state: st, latestMessage: m }); for (const [id, q, o] of items) r('addItemToCart', { itemId: id, quantity: q, options: o }); r('setOrderType', { orderType: 'delivery' }); r('setCustomerDetails', { name: 'Ali', phone: '03211234567', block: '3', houseOrFlat: '12-B', street: 'Street 4', noExtraAddressDetails: true }); r('readBackAddress', {}); return { st, r }; };
let { st, r } = mk([['ROL01', 1, [{ name: 'chutney', choice: 'with' }]]]); let y = r('confirmAddress', {}, 'haan, sahi hai');
assert.strictEqual(y.ok, true); assert.strictEqual(y.cartItems, 1); assert.strictEqual(y.reviewReady, true); assert.strictEqual(y.customerMessage, 'Thank you, your delivery address is confirmed. Your cart has 1 item and the order is ready for review.'); assert(y.internalNote.includes('The cart is NOT empty: never ask what the customer wants to order') && y.internalNote.includes('getOrderReview'));
({ st, r } = mk([['BRY01', 2, [{ name: 'spice', choice: 'mild' }]], ['RAI01', 1]])); y = r('confirmAddress', {}, 'yes'); assert.strictEqual(y.cartItems, 3); assert(y.customerMessage.includes('Your cart has 3 items and the order is ready for review.'));
// not confirmed (not a clear yes): no cart status at all, nothing changes
({ st, r } = mk([['NAN01', 1]])); y = r('confirmAddress', {}, 'ok'); assert.strictEqual(y.ok, false); assert(!('cartItems' in y)); assert.strictEqual(st.addressConfirmed, false);
// empty cart (the customer removed everything): told to ask what to order; review not ready
({ st, r } = mk([['NAN01', 1]])); r('removeItem', { itemId: 'NAN01' }); r('readBackAddress', {}); y = r('confirmAddress', {}, 'yes'); assert.strictEqual(y.ok, true); assert.strictEqual(y.cartItems, 0); assert.strictEqual(y.reviewReady, false); assert.strictEqual(y.customerMessage, 'Thank you, your delivery address is confirmed. Your cart is empty.'); assert(y.internalNote.includes('The cart is empty: ask what the customer would like to order'));
console.log('1) confirmAddress ok now reports the real cart: "Your cart has 1 item and the order is ready for review." (3 items for 2 biryani + raita), with a note to offer the review / more items and never ask what to order; "ok" confirms nothing and adds no cart text; an empty cart says so and may ask what to order: PASS');
const prompt = fs.readFileSync(ROOT + '/prompts/system-prompt.md', 'utf8'); for (const t of ['After the address is confirmed, continue from the real cart', 'offer to show the order review or ask if they want to add anything else', 'never ask "what would you like to order" when the cart is not empty']) assert(prompt.includes(t), t);
// whole chat turn: the stub model repeats the tool's customerMessage, the reply continues from the cart and the review is next
global.__STUB = async ({ contents }) => { const res = L.lastToolResults(contents); if (res) return L.text(res[res.length - 1].response.customerMessage); return L.calls([{ name: 'confirmAddress' }], null); };
(async () => { await new Promise(x => setTimeout(x, 400)); const a = await L.post(base, { message: 'hi' }); const s2 = sessions.getOrCreateSession(a.json.sessionId).state; const q = (n, args) => executeTool(n, args, { state: s2 }); q('addItemToCart', { itemId: 'ROL01', quantity: 1, options: [{ name: 'chutney', choice: 'with' }] }); q('setOrderType', { orderType: 'delivery' }); q('setCustomerDetails', { name: 'Ali', phone: '03211234567', block: '3', houseOrFlat: '12-B', street: 'Street 4', noExtraAddressDetails: true }); q('readBackAddress', {});
  const resp = await L.post(base, { message: 'haan, sahi hai', sessionId: a.json.sessionId }); assert.strictEqual(resp.json.reply, 'Thank you, your delivery address is confirmed. Your cart has 1 item and the order is ready for review.'); assert(!/what would you like to order/i.test(resp.json.reply)); assert.strictEqual(s2.addressConfirmed, true); assert.strictEqual(s2.status, 'draft');
  console.log('2) the prompt has the rule; a chat turn with "haan, sahi hai" answers with the cart status, the address flag is set and nothing is saved: PASS'); console.log('ALL STEP-AW TESTS PASSED'); process.exit(0); })().catch(e => { console.error('TEST FAILED:', e.stack.split('\n').slice(0, 8).join('\n')); process.exit(1); });
