const ROOT = require('path').join(__dirname, '..', '..');
// Step AY: WhatsApp order channel (demo): same confirm gate, a wa.me link built by code, nothing stored
const assert = require('assert'); const fs = require('fs'); const L = require('./lib.js'); const { sessions, base } = L.boot(3107);
const wa = require(ROOT + '/backend/whatsapp'); const { executeTool } = require(ROOT + '/backend/tools'); const { orderChannel } = require(ROOT + '/backend/config');
const sleep = (ms) => new Promise(r => setTimeout(r, ms)); const run = (st, n, a, m) => executeTool(n, a, { state: st, latestMessage: m });
// ---- number normalisation ----
for (const [raw, want] of [['03001234567', '923001234567'], ['0300 1234567', '923001234567'], ['0300-1234567', '923001234567'], ['+923001234567', '923001234567'], ['+92 300 1234567', '923001234567'], ['923001234567', '923001234567'], ['92-300-1234567', '923001234567'], [' (0300) 123 4567 ', '923001234567'], ['03211234567', '923211234567']]) assert.strictEqual(wa.normalizeNumber(raw), want, raw);
for (const bad of ['', undefined, null, 5, '0300123456', '030012345678', '+92300123456', '+9230012345678', '02001234567', '+913001234567', '923001234', 'abc', '0300 12345 67 8', '+92 3001234567 x', '00923001234567', '+1 555 123 4567', '9230012345678']) assert.strictEqual(wa.normalizeNumber(bad), null, String(bad));
assert(/^KD-[0-9A-F]{5}$/.test(wa.newRef())); assert.notStrictEqual(wa.newRef(), wa.newRef()); assert.strictEqual(wa.HEADER, '[DEMO] کراچی دسترخوان — کورس کا ٹیسٹ آرڈر');
for (const [v, want] of [[undefined, 'file'], ['', 'file'], ['file', 'file'], ['whatsapp', 'whatsapp'], [' WhatsApp ', 'whatsapp'], ['WHATSAPP', 'whatsapp'], ['sms', 'file'], ['whats app', 'file']]) { if (v === undefined) delete process.env.ORDER_CHANNEL; else process.env.ORDER_CHANNEL = v; assert.strictEqual(orderChannel(), want, String(v)); }
console.log('1) numbers: 03XXXXXXXXX, +923XXXXXXXXX, 923XXXXXXXXX (spaces, dashes, brackets ignored) -> 923XXXXXXXXX; 16 wrong forms -> null; refs look like KD-7F3A9 and differ; ORDER_CHANNEL is "file" unless it is whatsapp (any case): PASS');
const confirm = async (body) => { const r = await fetch(base + '/api/order/confirm', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); return { status: r.status, json: await r.json() }; };
const MILD = [{ name: 'spice', choice: 'mild' }]; const ordersCount = () => JSON.parse(fs.readFileSync(global.__ORDERS_FILE, 'utf8')).length; const dirFiles = () => fs.readdirSync(global.__ORDERS_DIR).sort().join(',');
let stub = 'hi'; global.__STUB = async ({ contents }) => { const res = L.lastToolResults(contents); if (res) return L.text(res[res.length - 1].response.customerMessage); return stub === 'review' ? L.calls([{ name: 'getOrderReview' }], null) : L.text(stub); };
const post = (message, sessionId) => L.post(base, { message, sessionId });
const ready = async (type) => { stub = 'hi'; const a = await post('hi'); const st = sessions.getOrCreateSession(a.json.sessionId).state; run(st, 'addItemToCart', { itemId: 'BRY01', quantity: 2, options: MILD }); run(st, 'addItemToCart', { itemId: 'RAI01', quantity: 1 });
  if (type === 'delivery') { run(st, 'setOrderType', { orderType: 'delivery' }); run(st, 'setCustomerDetails', { name: 'Sara Khan', phone: '03211234567', block: '3', houseOrFlat: '12-B', street: 'Street 4', apartment: 'Flat 2', instructions: 'ring twice', noExtraAddressDetails: true }); run(st, 'readBackAddress', {}); run(st, 'confirmAddress', {}, 'yes'); }
  else { run(st, 'setOrderType', { orderType: 'pickup' }); run(st, 'setCustomerDetails', { name: 'Hamza Ali', pickupTime: '19:30' }); }
  stub = 'review'; const rv = await post('review please', a.json.sessionId); return { sid: a.json.sessionId, st, rv: rv.json, review: rv.json.reply }; };
(async () => { await sleep(400); const logs = []; const ol = console.log, oe = console.error; console.log = (...a) => { logs.push(a.join(' ')); ol(...a); }; console.error = (...a) => { logs.push(a.join(' ')); oe(...a); };
  process.env.ORDERS_ENABLED = 'true'; process.env.ORDER_CHANNEL = 'whatsapp'; process.env.WHATSAPP_ORDER_NUMBER = '0300 1234567'; const files0 = dirFiles(); const n0 = ordersCount();
  // ---- pickup order -> link ----
  let o = await ready('pickup'); assert.match(o.rv.reviewVersion, /^[0-9a-f]{16}$/); let r = await confirm({ sessionId: o.sid, reviewVersion: o.rv.reviewVersion }); assert.strictEqual(r.status, 200, JSON.stringify(r.json));
  const j = r.json; assert.deepStrictEqual([j.ok, j.channel, j.sent, j.confirmed, j.saved], [true, 'whatsapp', false, false, false]); assert(!('orderId' in j)); assert(j.whatsapp.link.startsWith('https://wa.me/923001234567?text=')); assert(j.whatsapp.link.length < 2000);
  const text = decodeURIComponent(j.whatsapp.link.split('?text=')[1]); assert.strictEqual(text, j.whatsapp.message); const lines = text.split('\n'); assert.strictEqual(lines[0], '[DEMO] کراچی دسترخوان — کورس کا ٹیسٹ آرڈر'); assert.match(lines[1], /^Ref: KD-[0-9A-F]{5}$/); assert.strictEqual(lines[1], 'Ref: ' + j.whatsapp.ref);
  assert.deepStrictEqual(lines.slice(2), ['Items:', '2 x Chicken Biryani (spice: mild) - 700 PKR', '1 x Raita - 80 PKR', 'Food subtotal: 780 PKR', 'Total: 780 PKR', 'Order type: Pickup', 'Name: Hamza Ali', 'Preferred pickup time: 7:30 PM', 'Payment: cash on pickup']);
  assert(/NOT sent yet/.test(j.customerMessage) && j.customerMessage.includes('آپ کا آرڈر ابھی نہیں گیا') && !/\b(placed|received|confirmed)\b/i.test(j.customerMessage), j.customerMessage);
  assert.strictEqual(ordersCount(), n0); assert.strictEqual(dirFiles(), files0, 'nothing written to disk (no orders file change, no temp file)'); assert.strictEqual(o.st.status, 'draft'); assert.strictEqual(o.st.orderId, null);
  // totals in the message equal the review the customer saw
  assert(o.review.includes('Total: 780 PKR') && text.includes('Total: 780 PKR'));
  // idempotent: same reviewVersion -> same link and ref
  const again = await confirm({ sessionId: o.sid, reviewVersion: o.rv.reviewVersion }); assert.strictEqual(again.status, 200); assert.strictEqual(again.json.whatsapp.link, j.whatsapp.link); assert.strictEqual(again.json.whatsapp.ref, j.whatsapp.ref); assert.strictEqual(ordersCount(), n0);
  console.log('2) pickup order: the same gate, then {channel: whatsapp, sent: false, saved: false} with a https://wa.me/923001234567?text=... link; the text starts with the [DEMO] header, "Ref: KD-XXXXX", items with options and line totals, subtotal, total, pickup time, payment; totals equal the review; the NOT-sent notice in English and Urdu never says placed/received; orders file and folder untouched; the same reviewVersion twice -> the same link and ref: PASS');
  // the button disappears for this review; changing the cart makes the old version outdated and a new review gets a new link
  stub = 'hi'; const after = await post('thanks', o.sid); assert.strictEqual(after.json.reviewVersion, null, 'no button again for a review whose link exists');
  run(o.st, 'addItemToCart', { itemId: 'NAN01', quantity: 1 }); const stale = await confirm({ sessionId: o.sid, reviewVersion: o.rv.reviewVersion }); assert.strictEqual(stale.status, 409); assert.strictEqual(stale.json.error, 'review_outdated'); stub = 'review'; const rv2 = await post('review please', o.sid); assert.match(rv2.json.reviewVersion, /^[0-9a-f]{16}$/); const r2 = await confirm({ sessionId: o.sid, reviewVersion: rv2.json.reviewVersion }); assert.strictEqual(r2.status, 200); assert.notStrictEqual(r2.json.whatsapp.ref, j.whatsapp.ref); assert(decodeURIComponent(r2.json.whatsapp.link.split('?text=')[1]).includes('1 x Naan - 40 PKR') && r2.json.whatsapp.message.includes('Total: 820 PKR'));
  // ---- the gate is unchanged ----
  let g = await ready('pickup'); for (const body of [{ sessionId: g.sid, reviewVersion: '0'.repeat(16) }, { sessionId: g.sid }, { reviewVersion: g.rv.reviewVersion }, { sessionId: 'f'.repeat(32), reviewVersion: g.rv.reviewVersion }]) { const x = await confirm(body); assert(x.status >= 400 && !x.json.whatsapp, JSON.stringify(body)); }
  stub = 'yes'; await post('yes', g.sid); await post('ok', g.sid); assert.strictEqual(logs.filter(l => l === 'Order confirm: WhatsApp link ready').length, 3, 'typing "yes" / "ok" never produced a link');
  const noReview = (() => { const st = sessions.getOrCreateSession().state; run(st, 'addItemToCart', { itemId: 'NAN01', quantity: 1 }); run(st, 'setOrderType', { orderType: 'pickup' }); run(st, 'setCustomerDetails', { name: 'Ali' }); return st; })(); // review never shown
  const nr = sessions.getOrCreateSession(); assert(nr);
  // delivery: address must be confirmed first (review not ready), then everything is in the text
  stub = 'hi'; const d0 = await post('hi'); const dst = sessions.getOrCreateSession(d0.json.sessionId).state; run(dst, 'addItemToCart', { itemId: 'ROL01', quantity: 1, options: [{ name: 'chutney', choice: 'with' }] }); run(dst, 'setOrderType', { orderType: 'delivery' }); run(dst, 'setCustomerDetails', { name: 'Ali', phone: '03211234567', block: '3', houseOrFlat: '12-B', street: 'Street 4', noExtraAddressDetails: true });
  const early = await confirm({ sessionId: d0.json.sessionId, reviewVersion: 'a'.repeat(16) }); assert.strictEqual(early.status, 409); assert(!early.json.whatsapp);
  let d = await ready('delivery'); r = await confirm({ sessionId: d.sid, reviewVersion: d.rv.reviewVersion }); assert.strictEqual(r.status, 200); const dt = r.json.whatsapp.message; for (const want of ['2 x Chicken Biryani (spice: mild) - 700 PKR', 'Food subtotal: 780 PKR', 'Delivery fee: 150 PKR', 'Total: 930 PKR', 'Order type: Delivery', 'Name: Sara Khan', 'Phone: 03211234567', 'Address: House or flat 12-B, Street 4, Block 3, Gulshan-e-Iqbal, Karachi', 'Apartment or unit: Flat 2', 'Delivery instructions: ring twice', 'Payment: cash on delivery']) assert(dt.split('\n').includes(want), want + '\n' + dt);
  // discount line
  stub = 'hi'; const p0 = await post('hi'); const pst = sessions.getOrCreateSession(p0.json.sessionId).state; run(pst, 'addItemToCart', { itemId: 'BRY01', quantity: 2, options: MILD }); run(pst, 'setOrderType', { orderType: 'pickup' }); run(pst, 'setCustomerDetails', { name: 'Ali', noPickupTimePreference: true }); run(pst, 'applyPromotion', { code: 'PICKUP50' }); stub = 'review'; const prv = await post('review', p0.json.sessionId); const pr = await confirm({ sessionId: p0.json.sessionId, reviewVersion: prv.json.reviewVersion }); const pl = pr.json.whatsapp.message.split('\n'); assert(pl.includes('Discount (PICKUP50): -50 PKR') && pl.includes('Food subtotal: 700 PKR') && pl.includes('Total: 650 PKR') && !pl.some(l => l.startsWith('Delivery fee') || l.startsWith('Preferred pickup')));
  console.log('3) the gate is unchanged (wrong/missing version, unknown session, typing yes/ok, review not ready -> no link); delivery text has phone, address, apartment, instructions, delivery fee, cash on delivery; a promo shows "Discount (PICKUP50): -50 PKR"; a changed cart makes the old version outdated and the next review gets a new ref; the button is not offered again for a review whose link exists: PASS');
  // ---- fail closed ----
  const keepNumber = process.env.WHATSAPP_ORDER_NUMBER; for (const bad of [undefined, '', '12345', 'abc', '+1 555 123 4567']) { if (bad === undefined) delete process.env.WHATSAPP_ORDER_NUMBER; else process.env.WHATSAPP_ORDER_NUMBER = bad; const x = await confirm({ sessionId: o.sid, reviewVersion: rv2.json.reviewVersion }); assert.deepStrictEqual([x.status, x.json.error], [503, 'whatsapp_not_configured'], String(bad)); assert(!x.json.whatsapp); }
  process.env.WHATSAPP_ORDER_NUMBER = keepNumber; process.env.ORDERS_ENABLED = 'false'; const off = await confirm({ sessionId: o.sid, reviewVersion: rv2.json.reviewVersion }); assert.strictEqual(off.json.error, 'ordering_disabled'); process.env.ORDERS_ENABLED = 'true';
  process.env.ORDER_CHANNEL = 'file'; process.env.VERCEL = '1'; process.env.SESSION_SECRET = 'v'.repeat(40); const vf = await confirm({ sessionId: o.sid, reviewVersion: rv2.json.reviewVersion }); assert.deepStrictEqual([vf.status, vf.json.error], [503, 'file_orders_not_supported_on_vercel']); assert.strictEqual(ordersCount(), n0);
  process.env.ORDER_CHANNEL = 'whatsapp'; const vw = await confirm({ sessionId: o.sid, reviewVersion: rv2.json.reviewVersion }); assert.strictEqual(vw.status, 200, 'WhatsApp works on Vercel (nothing is stored)'); delete process.env.VERCEL; delete process.env.SESSION_SECRET;
  for (const l of logs.filter(x => !/^\d\) /.test(x))) { assert(!/923001234567|03001234567|0300 1234567|wa\.me/.test(l), 'the number or link is never logged: ' + l); }
  console.log('4) fail closed: missing or invalid WHATSAPP_ORDER_NUMBER -> 503 whatsapp_not_configured; ORDERS_ENABLED off -> ordering_disabled first; VERCEL=1 with the file channel -> 503 file_orders_not_supported_on_vercel (nothing written), with the WhatsApp channel it works; the number and link never appear in the logs: PASS');
  // ---- guard + model note ----
  let sys = ''; global.__STUB = async ({ contents, config }) => { sys = config.systemInstruction; return L.text('Your order is confirmed and sent to the kitchen!'); };
  const gr = await post('is it sent?', o.sid); assert(gr.json.reply.startsWith('Your order has not been placed yet'), 'a link is NOT a sent order: the guard still replaces the claim: ' + gr.json.reply); assert(sys.includes('## Order channel: WhatsApp (demo)') && sys.includes('Never say or imply that an order was placed, confirmed, sent, received or saved'));
  process.env.ORDER_CHANNEL = 'file'; await post('x', o.sid); assert(!sys.includes('Order channel: WhatsApp'), 'file mode: no WhatsApp note'); process.env.ORDER_CHANNEL = 'whatsapp';
  console.log = ol; console.error = oe; console.log('5) the fake-confirmation guard still replaces "order confirmed / sent" claims in WhatsApp mode (a generated link is not a sent order) and the model is told never to claim it; no WhatsApp note in file mode: PASS'); console.log('ALL STEP-AY TESTS PASSED'); process.exit(0);
})().catch(e => { console.error('TEST FAILED:', e.stack.split('\n').slice(0, 10).join('\n')); process.exit(1); });
