const ROOT = require('path').join(__dirname, '..', '..');
// Step BB: every field of setCustomerDetails is validated on its own; an invented name no longer drops the address (reproduces the real S1 sequence)
const assert = require('assert'); const fs = require('fs'); const L = require('./lib.js'); const { sessions, base } = L.boot(3108);
const { executeTool, TOOL_DECLARATIONS } = require(ROOT + '/backend/tools');
const mk = () => { const st = sessions.getOrCreateSession().state; const r = (n, a, m) => executeTool(n, a, { state: st, latestMessage: m }); r('addItemToCart', { itemId: 'ROL01', quantity: 1, options: [{ name: 'chutney', choice: 'with' }] }); r('setOrderType', { orderType: 'delivery' }); return { st, r }; };
const addr = (st) => { const a = st.customer.address || {}; return [a.block, a.house, a.street]; };
// 1) invalid name + valid address: address stored, name not stored, the result says to ask for the name
let { st, r } = mk(); let x = r('setCustomerDetails', { name: 'Gulshan', block: 3, houseOrFlat: '12-B', street: '4' });
assert.strictEqual(x.ok, true); assert.deepStrictEqual(addr(st), [3, '12-B', '4']); assert.strictEqual(st.customer.name, null); assert.deepStrictEqual(x.stored.sort(), ['block', 'house', 'street']); assert.deepStrictEqual(x.rejectedFields.map(f => [f.field, f.error]), [['name', 'invalid_name']]); assert(x.missingDetails.some(m => m.field === 'name') && x.missingDetails.some(m => m.field === 'phone'));
assert(x.internalNote.includes('name_not_stored: the customer has not given a name - ask for it; never invent one')); assert(x.customerMessage.includes('May I have your name'), x.customerMessage); assert(!x.customerMessage.includes("didn't catch that name"), 'one question for the name, not two');
// 2) outside area + invented name: reported, nothing stored
({ st, r } = mk()); x = r('setCustomerDetails', { name: 'Gulshan', block: 9, houseOrFlat: '12', street: 'Street 4' }); assert.strictEqual(x.ok, false); assert.strictEqual(x.error, 'outside_delivery_area'); assert(x.customerMessage.startsWith('Sorry, we deliver only to Gulshan-e-Iqbal Blocks 1 to 5.') && /pickup/i.test(x.customerMessage)); assert.strictEqual(st.customer.name, null); assert.strictEqual(st.customer.address, null); assert.strictEqual(st.orderType, 'delivery', 'the order type is not switched'); assert(x.rejectedFields.some(f => f.error === 'outside_delivery_area') && x.rejectedFields.some(f => f.error === 'invalid_name'));
// 3) valid name + bad phone: name stored, phone rejected with its own reason
({ st, r } = mk()); x = r('setCustomerDetails', { name: 'Ali', phone: '12345' }); assert.strictEqual(x.ok, true); assert.strictEqual(st.customer.name, 'Ali'); assert.strictEqual(st.customer.phone, null); assert.deepStrictEqual(x.rejectedFields.map(f => [f.field, f.error]), [['phone', 'invalid_phone']]); assert(x.customerMessage.includes('Please share it like 03XX XXXXXXX.')); assert(x.stored.includes('name') && !x.stored.includes('phone'));
// 4) valid name + phone with an address outside the area: the refusal is the answer, name and phone are kept, no part of the address
({ st, r } = mk()); x = r('setCustomerDetails', { name: 'Ali', phone: '03211234567', block: 9, houseOrFlat: '12', street: 'Street 4' }); assert.strictEqual(x.ok, false); assert.strictEqual(x.error, 'outside_delivery_area'); assert.deepStrictEqual([st.customer.name, st.customer.phone], ['Ali', '03211234567']); assert.strictEqual(st.customer.address, null); assert(x.stored.includes('name') && x.stored.includes('phone')); assert(/Offer pickup, but do not switch/.test(x.internalNote) || x.internalNote.includes('outside_delivery_area'));
// 5) several bad fields at once: each is reported on its own, the good ones are kept
({ st, r } = mk()); x = r('setCustomerDetails', { name: 'Chicken Roll', phone: '0300', block: 'abc', houseOrFlat: '12-B', street: '<b>' }); assert.strictEqual(x.ok, true); assert.deepStrictEqual(x.rejectedFields.map(f => f.field).sort(), ['block', 'name', 'phone', 'street']); assert.deepStrictEqual(x.stored, ['house']); assert.strictEqual(st.customer.address.house, '12-B');
({ st, r } = mk()); x = r('setCustomerDetails', { name: 'Gulshan', phone: '0300' }); assert.strictEqual(x.ok, false); assert.strictEqual(x.error, 'invalid_name', 'nothing could be stored: the first reason is the answer'); assert.deepStrictEqual(x.rejectedFields.map(f => f.field), ['name', 'phone']); assert.strictEqual(st.customer.name, null);
// an already stored good name survives a later invalid one
({ st, r } = mk()); r('setCustomerDetails', { name: 'Hamza' }); x = r('setCustomerDetails', { name: 'Naan', block: 3 }); assert.strictEqual(x.ok, true); assert.strictEqual(st.customer.name, 'Hamza'); assert.strictEqual(st.customer.address.block, 3);
// pickup: a bad pickup time does not drop the name either; delivery fields are still just ignored
{ const p = sessions.getOrCreateSession().state; const q = (n, a) => executeTool(n, a, { state: p }); q('addItemToCart', { itemId: 'NAN01', quantity: 1 }); q('setOrderType', { orderType: 'pickup' }); const y = q('setCustomerDetails', { name: 'Ali', pickupTime: '23:30' }); assert.strictEqual(y.ok, true); assert.strictEqual(p.customer.name, 'Ali'); assert.strictEqual(p.pickupTime, null); assert(y.rejectedFields.some(f => f.field === 'pickupTime')); const z = q('setCustomerDetails', { name: 'Pickup', pickupTime: '19:30' }); assert.strictEqual(z.ok, true); assert.strictEqual(p.customer.name, 'Ali'); assert.strictEqual(p.pickupTime, '19:30'); }
console.log('1) {name:"Gulshan", block 3, house 12-B, street 4} -> address stored, name not stored, "name_not_stored: ... ask for it; never invent one", name asked once; {name:"Gulshan", block 9} -> OUTSIDE_DELIVERY_AREA reported with pickup offered, nothing stored, order type unchanged; {name:"Ali", phone:"12345"} -> name stored, phone INVALID_PHONE; valid name + phone with block 9 -> refusal answer, name and phone kept, no address; several bad fields are each reported while good ones stay; a good stored name survives a later invalid one; a bad pickup time does not drop the name: PASS');
// 6) the real live sequence through the chat: a model that sends an invented name with every address message
const calls = { 'deliver to Gulshan': { name: 'Gulshan', area: 'Gulshan' }, 'Block 9 house 12 Street 4': { name: 'Gulshan', block: '9', houseOrFlat: '12', street: 'Street 4' }, 'Block 3, house 12-B, Street 4': { name: 'Gulshan', block: '3', houseOrFlat: '12-B', street: 'Street 4' }, '03211234567': { name: 'Gulshan', phone: '03211234567' }, 'Ali': { name: 'Ali' } };
global.__STUB = async ({ contents }) => { const res = L.lastToolResults(contents); if (res) return L.text(res[res.length - 1].response.customerMessage); const said = contents[contents.length - 1].parts.map(p => p.text || '').join(' '); return calls[said] ? L.calls([{ name: 'setCustomerDetails', args: calls[said] }], null) : L.text('ok'); };
(async () => { await new Promise(rr => setTimeout(rr, 400)); const a = await L.post(base, { message: 'hi' }); const sid = a.json.sessionId; const s2 = sessions.getOrCreateSession(sid).state; const q = (n, args) => executeTool(n, args, { state: s2 }); q('addItemToCart', { itemId: 'ROL01', quantity: 1, options: [{ name: 'chutney', choice: 'with' }] }); q('setOrderType', { orderType: 'delivery' });
  const say = (m) => L.post(base, { message: m, sessionId: sid }).then(x => x.json.reply);
  await say('deliver to Gulshan'); assert.strictEqual(s2.customer.name, null); let reply = await say('Block 9 house 12 Street 4'); assert(reply.startsWith('Sorry, we deliver only to Gulshan-e-Iqbal Blocks 1 to 5.'), 'the customer IS told that block 9 is outside the area: ' + reply); assert.strictEqual(s2.customer.address, null);
  await say('Block 3, house 12-B, Street 4'); assert.deepStrictEqual(addr(s2), [3, '12-B', 'Street 4'], 'the valid address is no longer lost'); assert.strictEqual(s2.customer.name, null); await say('03211234567'); assert.strictEqual(s2.customer.phone, '03211234567'); assert.strictEqual(s2.customer.name, null);
  const rb0 = q('readBackAddress', {}); assert.strictEqual(rb0.ok, false, 'no read-back without a real name'); await say('Ali'); assert.strictEqual(s2.customer.name, 'Ali'); const rb = q('readBackAddress', {}); assert(rb.customerMessage.includes('Name: Ali') && !rb.customerMessage.includes('Name: Gulshan'));
  const nameParam = TOOL_DECLARATIONS.find(d => d.name === 'setCustomerDetails').parameters.properties.name.description; for (const t of ['OPTIONAL', 'only if the customer said their name in their own words', 'Leave this out otherwise', 'never invent one']) assert(nameParam.includes(t), t);
  console.log('2) the real S1 sequence with a model that sends the invented name "Gulshan" every time: "deliver to Gulshan" stores nothing, "Block 9 house 12 Street 4" -> the customer is told it is outside the area, "Block 3, house 12-B, Street 4" is KEPT, the phone is kept, no read-back until "Ali" gives a real name, the read-back shows "Name: Ali"; the tool description says the name is optional and must be left out unless the customer said it: PASS'); console.log('ALL STEP-BB TESTS PASSED'); process.exit(0); })().catch(e => { console.error('TEST FAILED:', e.stack.split('\n').slice(0, 8).join('\n')); process.exit(1); });
